{{- if .Values.minio.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hiteam.fullname" . }}-minio-bucket
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 3
  template:
    spec:
      imagePullSecrets:
        - name: {{ .Values.sharedInfo.pullSecret.name }}
      restartPolicy: Never
      containers:
        - name: create-bucket
          image: {{ .Values.minio.mcImage | quote }}
          command:
            - sh
            - -c
            - |
              set -eu
              until /usr/bin/mc alias set local http://{{ include "hiteam.minioServiceName" . }}:{{ .Values.minio.service.port }} {{ .Values.minio.rootUser }} {{ .Values.minio.rootPassword }};
              do
                echo "waiting for minio";
                sleep 2;
              done;
              /usr/bin/mc mb --ignore-existing -p local/{{ .Values.minio.bucket }}
              printf '%s' {{ tpl (.Files.Get "files/minio-public-policy.json") . | fromJson | toJson | squote }} > /tmp/public-policy.json
              /usr/bin/mc anonymous set-json /tmp/public-policy.json local/{{ .Values.minio.bucket }}
{{- end }}
