{{- if .Values.sharedInfo.pullSecret.dockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hiteam.pullSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    project: {{ .Values.sharedInfo.project.name }}
    branch: {{ .Values.sharedInfo.project.branch }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.sharedInfo.pullSecret.dockerConfigJson | quote }}
{{- end }}
