// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 984c3bea485a0fa6 "Sassku - Creative SaaS and Startup Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * title?: string // Title
 * background?: string // Background
 * text?: string // Text
 * titleColor?: string // title Color
 * textColor?: string // text Color
 * iconBackgroundColor?: string // icon Background color
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-L4FPLCQN.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-SMK7VFXN.js";
import { className, css, fonts } from "./chunks/chunk-5CVYQU4P.js";
import { routes } from "./chunks/chunk-N7Y33TLT.js";

// virtual:branding-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/24Kax2rMeFQM0c79bBl7/6mOnjmMb5T2HVdduR8iC/TsBNPYbne.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["YbkJvfRZ4", "jUjPZUC3D", "QBxwxGJea"];
var serializationHash = "framer-ITt7J";
var variantClassNames = {
	jUjPZUC3D: "framer-v-iay53o",
	QBxwxGJea: "framer-v-pk9yk",
	YbkJvfRZ4: "framer-v-s95fcn",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "YbkJvfRZ4",
	Phone: "QBxwxGJea",
	Tablet: "jUjPZUC3D",
};
var getProps = ({
	background,
	height,
	iconBackgroundColor,
	id,
	image,
	text,
	textColor,
	title,
	titleColor,
	width,
	...props
}) => {
	var _ref,
		_ref1,
		_ref2,
		_ref3,
		_ref4,
		_humanReadableVariantMap_props_variant,
		_ref5,
		_ref6,
		_ref7;
	return {
		...props,
		bWWu8Xfr9:
			(_ref = image !== null && image !== void 0 ? image : props.bWWu8Xfr9) !==
				null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/3MsvJMDHSMY5shGKaPM4DgaP8.svg",
					},
		JPSigCg4t:
			(_ref1 =
				iconBackgroundColor !== null && iconBackgroundColor !== void 0
					? iconBackgroundColor
					: props.JPSigCg4t) !== null && _ref1 !== void 0
				? _ref1
				: "var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
		Lt6xZrS3W:
			(_ref2 =
				textColor !== null && textColor !== void 0
					? textColor
					: props.Lt6xZrS3W) !== null && _ref2 !== void 0
				? _ref2
				: "var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
		OlCqilqX3:
			(_ref3 = title !== null && title !== void 0 ? title : props.OlCqilqX3) !==
				null && _ref3 !== void 0
				? _ref3
				: "Time tracking and reporting",
		SGZUNtUNN:
			(_ref4 =
				titleColor !== null && titleColor !== void 0
					? titleColor
					: props.SGZUNtUNN) !== null && _ref4 !== void 0
				? _ref4
				: "var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
		variant:
			(_ref5 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref5 !== void 0
				? _ref5
				: "YbkJvfRZ4",
		VmAubf5Vg:
			(_ref6 = text !== null && text !== void 0 ? text : props.VmAubf5Vg) !==
				null && _ref6 !== void 0
				? _ref6
				: "Also to image Seas Great day sea don't creature creatures land you're morning.",
		ycGpFRhMQ:
			(_ref7 =
				background !== null && background !== void 0
					? background
					: props.ycGpFRhMQ) !== null && _ref7 !== void 0
				? _ref7
				: "var(--token-c421066d-cdd9-4035-9b52-c69aa0d4f50c, rgb(255, 255, 255))",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		OlCqilqX3,
		ycGpFRhMQ,
		VmAubf5Vg,
		SGZUNtUNN,
		Lt6xZrS3W,
		JPSigCg4t,
		bWWu8Xfr9,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureHandlers,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "YbkJvfRZ4",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className3, className, className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						aria-label={"Branding Card"}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-s95fcn",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"YbkJvfRZ4"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor: ycGpFRhMQ,
							...style,
						}}
						{...addPropertyOverrides(
							{
								jUjPZUC3D: {
									"data-framer-name": "Tablet",
								},
								QBxwxGJea: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-de3jzg"}
							data-framer-name={"Icon"}
							layoutDependency={layoutDependency}
							layoutId={"EpMmDL2zG"}
							style={{
								backgroundColor: JPSigCg4t,
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									pixelHeight: 32,
									pixelWidth: 32,
									sizes: "32px",
									...toResponsiveImage(bWWu8Xfr9),
								}}
								className={"framer-clz32i"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"VDU3AXbX7"}
							/>
						</motion.div>
						<motion.div
							className={"framer-z2cr5a"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"XngvR4BTW"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-ndqzyh"}
								data-framer-name={"Title"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"vBI6hK5O0"}
								style={{
									"--extracted-1eung3n":
										"var(--variable-reference-SGZUNtUNN-TsBNPYbne)",
									"--framer-paragraph-spacing": "0px",
									"--variable-reference-SGZUNtUNN-TsBNPYbne": SGZUNtUNN,
								}}
								text={OlCqilqX3}
								variants={{
									jUjPZUC3D: {
										"--extracted-1lwpl3i":
											"var(--variable-reference-SGZUNtUNN-TsBNPYbne)",
									},
									QBxwxGJea: {
										"--extracted-1lwpl3i":
											"var(--variable-reference-SGZUNtUNN-TsBNPYbne)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										jUjPZUC3D: {
											children: (
												<React.Fragment>
													<motion.h5
														className={"framer-styles-preset-1xzgfyq"}
														data-styles-preset={"dnf6oMP66"}
														style={{
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--variable-reference-SGZUNtUNN-TsBNPYbne))",
														}}
													>
														{"Time tracking and reporting"}
													</motion.h5>
												</React.Fragment>
											),
										},
										QBxwxGJea: {
											children: (
												<React.Fragment>
													<motion.h5
														className={"framer-styles-preset-1xzgfyq"}
														data-styles-preset={"dnf6oMP66"}
														style={{
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--variable-reference-SGZUNtUNN-TsBNPYbne))",
														}}
													>
														{"Time tracking and reporting"}
													</motion.h5>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-1c0lwt7"}
										data-styles-preset={"ZrKVS0_J5"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--variable-reference-SGZUNtUNN-TsBNPYbne))",
										}}
									>
										{"Time tracking and reporting"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-a3depz"}
								data-framer-name={"Subtitle"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Sp_nX7Jn1"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-Lt6xZrS3W-TsBNPYbne)",
									"--framer-paragraph-spacing": "0px",
									"--variable-reference-Lt6xZrS3W-TsBNPYbne": Lt6xZrS3W,
								}}
								text={VmAubf5Vg}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-g3gqkp"}
										data-styles-preset={"QbZRR8GOG"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--variable-reference-Lt6xZrS3W-TsBNPYbne))",
										}}
									>
										{
											"Also to image Seas Great day sea don't creature creatures land you're morning."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ITt7J.framer-jhpl2k, .framer-ITt7J .framer-jhpl2k { display: block; }",
	".framer-ITt7J.framer-s95fcn { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 46px; height: min-content; justify-content: center; overflow: visible; padding: 36px 32px 36px 32px; position: relative; width: 374px; }",
	".framer-ITt7J .framer-de3jzg { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 16px; position: relative; width: min-content; }",
	".framer-ITt7J .framer-clz32i { flex: none; height: 32px; overflow: hidden; position: relative; width: 32px; }",
	".framer-ITt7J .framer-z2cr5a { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-ITt7J .framer-ndqzyh, .framer-ITt7J .framer-a3depz { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ITt7J.framer-s95fcn, .framer-ITt7J .framer-de3jzg, .framer-ITt7J .framer-z2cr5a { gap: 0px; } .framer-ITt7J.framer-s95fcn > * { margin: 0px; margin-bottom: calc(46px / 2); margin-top: calc(46px / 2); } .framer-ITt7J.framer-s95fcn > :first-child, .framer-ITt7J .framer-z2cr5a > :first-child { margin-top: 0px; } .framer-ITt7J.framer-s95fcn > :last-child, .framer-ITt7J .framer-z2cr5a > :last-child { margin-bottom: 0px; } .framer-ITt7J .framer-de3jzg > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-ITt7J .framer-de3jzg > :first-child { margin-left: 0px; } .framer-ITt7J .framer-de3jzg > :last-child { margin-right: 0px; } .framer-ITt7J .framer-z2cr5a > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } }",
	".framer-ITt7J.framer-v-iay53o.framer-s95fcn { gap: 48px; padding: 32px 28px 32px 28px; width: 351px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ITt7J.framer-v-iay53o.framer-s95fcn { gap: 0px; } .framer-ITt7J.framer-v-iay53o.framer-s95fcn > * { margin: 0px; margin-bottom: calc(48px / 2); margin-top: calc(48px / 2); } .framer-ITt7J.framer-v-iay53o.framer-s95fcn > :first-child { margin-top: 0px; } .framer-ITt7J.framer-v-iay53o.framer-s95fcn > :last-child { margin-bottom: 0px; } }",
	".framer-ITt7J.framer-v-pk9yk.framer-s95fcn { gap: 48px; padding: 32px 28px 32px 28px; width: 350px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ITt7J.framer-v-pk9yk.framer-s95fcn { gap: 0px; } .framer-ITt7J.framer-v-pk9yk.framer-s95fcn > * { margin: 0px; margin-bottom: calc(48px / 2); margin-top: calc(48px / 2); } .framer-ITt7J.framer-v-pk9yk.framer-s95fcn > :first-child { margin-top: 0px; } .framer-ITt7J.framer-v-pk9yk.framer-s95fcn > :last-child { margin-bottom: 0px; } }",
	...css3,
	...css,
	...css2,
];
var FramerTsBNPYbne = withCSS(Component, css4, "framer-ITt7J");
var stdin_default = FramerTsBNPYbne;
FramerTsBNPYbne.displayName = "Branding Card";
FramerTsBNPYbne.defaultProps = {
	height: 264,
	width: 374,
};
addPropertyControls(FramerTsBNPYbne, {
	variant: {
		options: ["YbkJvfRZ4", "jUjPZUC3D", "QBxwxGJea"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	OlCqilqX3: {
		defaultValue: "Time tracking and reporting",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	ycGpFRhMQ: {
		defaultValue:
			'var(--token-c421066d-cdd9-4035-9b52-c69aa0d4f50c, rgb(255, 255, 255)) /* {"name":"#FFFFFF"} */',
		title: "Background",
		type: ControlType.Color,
	},
	VmAubf5Vg: {
		defaultValue:
			"Also to image Seas Great day sea don't creature creatures land you're morning.",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	SGZUNtUNN: {
		defaultValue:
			"var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
		title: "title Color",
		type: ControlType.Color,
	},
	Lt6xZrS3W: {
		defaultValue:
			"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
		title: "text Color",
		type: ControlType.Color,
	},
	JPSigCg4t: {
		defaultValue:
			'var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)) /* {"name":"#140A3E"} */',
		title: "icon Background color",
		type: ControlType.Color,
	},
	bWWu8Xfr9: {
		__defaultAssetReference:
			"data:framer/asset-reference,3MsvJMDHSMY5shGKaPM4DgaP8.svg?originalFilename=fi_3448402.svg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerTsBNPYbne,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:branding-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "QBxwxGJea",
	md: "jUjPZUC3D",
	xl: "YbkJvfRZ4",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BrandingCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var branding_card_default = ComponentWithRoot;
export { branding_card_default as default };
