// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 984c3bea485a0fa6 "Sassku - Creative SaaS and Startup Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Button' | 'Tablet' | 'Phone' // Variant
 * title?: string // Title
 * amount?: string // Amount
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * link?: string // Link
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-OSN6ONYI.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-ISAWCYQO.js";
import { className, css, fonts } from "./chunks/chunk-5CVYQU4P.js";
import { routes } from "./chunks/chunk-N7Y33TLT.js";

// virtual:call-us-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jxA3opP2Tyizi5UZdEbH/p4ymltkZsbphuUE6FN3Z/amQqX5zPk.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["zHfQhHFi1", "nIhIo1dfP", "ODCuFDam2"];
var serializationHash = "framer-vgHoT";
var variantClassNames = {
	nIhIo1dfP: "framer-v-q6998y",
	ODCuFDam2: "framer-v-1iqqo9k",
	zHfQhHFi1: "framer-v-kniyc",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 50,
};
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 50,
};
var transition2 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	Button: "zHfQhHFi1",
	Phone: "ODCuFDam2",
	Tablet: "nIhIo1dfP",
};
var getProps = ({
	amount,
	height,
	id,
	image,
	link,
	title,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _humanReadableVariantMap_props_variant, _ref3;
	return {
		...props,
		czun4Ysgb:
			(_ref =
				amount !== null && amount !== void 0 ? amount : props.czun4Ysgb) !==
				null && _ref !== void 0
				? _ref
				: "+01 598 269 4756",
		iCbtr0ls3:
			(_ref1 = image !== null && image !== void 0 ? image : props.iCbtr0ls3) !==
				null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/qJjo45fXEYFGWoDo9ZR3i5Dys.svg",
					},
		u4E0_NUi_:
			(_ref2 = title !== null && title !== void 0 ? title : props.u4E0_NUi_) !==
				null && _ref2 !== void 0
				? _ref2
				: "Call Us:",
		uyxgjVBZf: link !== null && link !== void 0 ? link : props.uyxgjVBZf,
		variant:
			(_ref3 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref3 !== void 0
				? _ref3
				: "zHfQhHFi1",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		u4E0_NUi_,
		czun4Ysgb,
		iCbtr0ls3,
		uyxgjVBZf,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureHandlers,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "zHfQhHFi1",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className2, className, className3];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__exit={animation1}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						aria-label={"Call Us Card"}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-kniyc",
							className4,
							classNames,
						)}
						data-framer-name={"Button"}
						layoutDependency={layoutDependency}
						layoutId={"zHfQhHFi1"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								nIhIo1dfP: {
									"data-framer-name": "Tablet",
								},
								ODCuFDam2: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-dasye5"}
							data-framer-name={"Content "}
							layoutDependency={layoutDependency}
							layoutId={"jycVaOo9n"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1smf08i"}
								data-framer-name={"Subtitle"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"tU4AIt6io"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={u4E0_NUi_}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-e8pqpa"}
										data-styles-preset={"IyWc0A25X"}
									>
										{"Call Us:"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-17n4mk2"}
								data-framer-name={"Title"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"mH06hd_aS"}
								style={{
									"--extracted-1lwpl3i":
										"var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={czun4Ysgb}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h5
										className={"framer-styles-preset-1xzgfyq"}
										data-styles-preset={"dnf6oMP66"}
										style={{
											"--framer-text-color":
												"var(--extracted-1lwpl3i, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)))",
										}}
									>
										<Link
											href={uyxgjVBZf}
											openInNewTab={false}
											smoothScroll={true}
										>
											<motion.a
												className={"framer-styles-preset-1wxyf0f"}
												data-styles-preset={"AV5lDhBeu"}
											>
												{"+01 598 269 4756"}
											</motion.a>
										</Link>
									</motion.h5>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-15up9r7"}
							layoutDependency={layoutDependency}
							layoutId={"aGTjxd0M2"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									pixelHeight: 40,
									pixelWidth: 40,
									...toResponsiveImage(iCbtr0ls3),
								}}
								className={"framer-1qi324w"}
								layoutDependency={layoutDependency}
								layoutId={"rCdhxcDFm"}
							/>
						</motion.div>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-vgHoT.framer-1xqtneb, .framer-vgHoT .framer-1xqtneb { display: block; }",
	".framer-vgHoT.framer-kniyc { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 28px 32px 28px 32px; position: relative; width: 554px; }",
	".framer-vgHoT .framer-dasye5 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-vgHoT .framer-1smf08i { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-vgHoT .framer-17n4mk2 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-vgHoT .framer-15up9r7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-vgHoT .framer-1qi324w { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 40px; min-width: 40px; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vgHoT.framer-kniyc, .framer-vgHoT .framer-dasye5, .framer-vgHoT .framer-15up9r7, .framer-vgHoT .framer-1qi324w { gap: 0px; } .framer-vgHoT.framer-kniyc > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-vgHoT.framer-kniyc > :first-child, .framer-vgHoT .framer-15up9r7 > :first-child, .framer-vgHoT .framer-1qi324w > :first-child { margin-left: 0px; } .framer-vgHoT.framer-kniyc > :last-child, .framer-vgHoT .framer-15up9r7 > :last-child, .framer-vgHoT .framer-1qi324w > :last-child { margin-right: 0px; } .framer-vgHoT .framer-dasye5 > * { margin: 0px; margin-bottom: calc(6px / 2); margin-top: calc(6px / 2); } .framer-vgHoT .framer-dasye5 > :first-child { margin-top: 0px; } .framer-vgHoT .framer-dasye5 > :last-child { margin-bottom: 0px; } .framer-vgHoT .framer-15up9r7 > *, .framer-vgHoT .framer-1qi324w > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
	".framer-vgHoT.framer-v-q6998y.framer-kniyc { gap: unset; justify-content: space-between; width: 714px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vgHoT.framer-v-q6998y.framer-kniyc { gap: 0px; } .framer-vgHoT.framer-v-q6998y.framer-kniyc > *, .framer-vgHoT.framer-v-q6998y.framer-kniyc > :first-child, .framer-vgHoT.framer-v-q6998y.framer-kniyc > :last-child { margin: 0px; } }",
	".framer-vgHoT.framer-v-1iqqo9k.framer-kniyc { padding: 24px; width: 350px; }",
	".framer-vgHoT.framer-v-1iqqo9k .framer-1smf08i { white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css2,
	...css,
	...css3,
];
var FrameramQqX5zPk = withCSS(Component, css4, "framer-vgHoT");
var stdin_default = FrameramQqX5zPk;
FrameramQqX5zPk.displayName = "Call Us Card";
FrameramQqX5zPk.defaultProps = {
	height: 114,
	width: 554,
};
addPropertyControls(FrameramQqX5zPk, {
	variant: {
		options: ["zHfQhHFi1", "nIhIo1dfP", "ODCuFDam2"],
		optionTitles: ["Button", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	u4E0_NUi_: {
		defaultValue: "Call Us:",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	czun4Ysgb: {
		defaultValue: "+01 598 269 4756",
		displayTextArea: false,
		title: "Amount",
		type: ControlType.String,
	},
	iCbtr0ls3: {
		__defaultAssetReference:
			"data:framer/asset-reference,qJjo45fXEYFGWoDo9ZR3i5Dys.svg?originalFilename=telephone-call.svg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	uyxgjVBZf: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FrameramQqX5zPk,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:call-us-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ODCuFDam2",
	md: "nIhIo1dfP",
	xl: "zHfQhHFi1",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CallUsCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var call_us_card_default = ComponentWithRoot;
export { call_us_card_default as default };
