// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 984c3bea485a0fa6 "Sassku - Creative SaaS and Startup Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * title?: string // Title
 * backgroundColor?: string // Background color
 * borderColor?: undefined // Border color
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * visible?: boolean // Visible
 * textColor?: string // Text Color
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-3UHWVJNE.js";
import { routes } from "./chunks/chunk-N7Y33TLT.js";

// virtual:caption-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/t4BGekVGbqzbMnkXHhgP/pwroSMgzaLq0GSzGX5ek/c8RabFrxb.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["Vbc9dCRFd", "z70rtAAt5"];
var serializationHash = "framer-ZS2a7";
var variantClassNames = {
	Vbc9dCRFd: "framer-v-3hfvhg",
	z70rtAAt5: "framer-v-8k86l2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 10,
};
var transition2 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "Vbc9dCRFd",
	"Variant 2": "z70rtAAt5",
};
var getProps = ({
	backgroundColor,
	borderColor,
	height,
	id,
	image,
	textColor,
	title,
	visible,
	width,
	...props
}) => {
	var _ref,
		_ref1,
		_ref2,
		_ref3,
		_ref4,
		_humanReadableVariantMap_props_variant,
		_ref5,
		_ref6;
	return {
		...props,
		Drur3Isxs:
			(_ref =
				backgroundColor !== null && backgroundColor !== void 0
					? backgroundColor
					: props.Drur3Isxs) !== null && _ref !== void 0
				? _ref
				: "rgb(255, 255, 255)",
		hbhrcWZS_:
			(_ref1 = image !== null && image !== void 0 ? image : props.hbhrcWZS_) !==
				null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/MZZ2JdlW7McaVjvNKQqwIxAAbk.svg",
					},
		Pli8bMfBJ:
			(_ref2 =
				visible !== null && visible !== void 0 ? visible : props.Pli8bMfBJ) !==
				null && _ref2 !== void 0
				? _ref2
				: true,
		siRsUxlcm:
			(_ref3 = title !== null && title !== void 0 ? title : props.siRsUxlcm) !==
				null && _ref3 !== void 0
				? _ref3
				: "Build better sass website",
		t3GkMWijW:
			(_ref4 =
				textColor !== null && textColor !== void 0
					? textColor
					: props.t3GkMWijW) !== null && _ref4 !== void 0
				? _ref4
				: "rgb(0, 0, 0)",
		variant:
			(_ref5 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref5 !== void 0
				? _ref5
				: "Vbc9dCRFd",
		Ywx6DZQYi:
			(_ref6 =
				borderColor !== null && borderColor !== void 0
					? borderColor
					: props.Ywx6DZQYi) !== null && _ref6 !== void 0
				? _ref6
				: {
						borderColor: "rgba(214, 217, 217, 1)",
						borderStyle: "solid",
						borderWidth: 0.5,
					},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		siRsUxlcm,
		Drur3Isxs,
		Ywx6DZQYi,
		hbhrcWZS_,
		Pli8bMfBJ,
		t3GkMWijW,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureHandlers,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Vbc9dCRFd",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const isDisplayed = (value) => {
		if (baseVariant === "z70rtAAt5") return false;
		return value;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	var _Ywx6DZQYi_borderBottomWidth,
		_Ywx6DZQYi_borderLeftWidth,
		_Ywx6DZQYi_borderRightWidth,
		_Ywx6DZQYi_borderTopWidth;
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__exit={animation1}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-3hfvhg",
							className2,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"Vbc9dCRFd"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": `${(_Ywx6DZQYi_borderBottomWidth = Ywx6DZQYi.borderBottomWidth) !== null && _Ywx6DZQYi_borderBottomWidth !== void 0 ? _Ywx6DZQYi_borderBottomWidth : Ywx6DZQYi.borderWidth}px`,
							"--border-color": Ywx6DZQYi.borderColor,
							"--border-left-width": `${(_Ywx6DZQYi_borderLeftWidth = Ywx6DZQYi.borderLeftWidth) !== null && _Ywx6DZQYi_borderLeftWidth !== void 0 ? _Ywx6DZQYi_borderLeftWidth : Ywx6DZQYi.borderWidth}px`,
							"--border-right-width": `${(_Ywx6DZQYi_borderRightWidth = Ywx6DZQYi.borderRightWidth) !== null && _Ywx6DZQYi_borderRightWidth !== void 0 ? _Ywx6DZQYi_borderRightWidth : Ywx6DZQYi.borderWidth}px`,
							"--border-style": Ywx6DZQYi.borderStyle,
							"--border-top-width": `${(_Ywx6DZQYi_borderTopWidth = Ywx6DZQYi.borderTopWidth) !== null && _Ywx6DZQYi_borderTopWidth !== void 0 ? _Ywx6DZQYi_borderTopWidth : Ywx6DZQYi.borderWidth}px`,
							backgroundColor: Drur3Isxs,
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
						variants={{
							z70rtAAt5: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
							},
						}}
						{...addPropertyOverrides(
							{
								z70rtAAt5: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed(Pli8bMfBJ) && (
							<Image
								background={{
									alt: "",
									fit: "fill",
									pixelHeight: 10,
									pixelWidth: 11,
									sizes: "10px",
									...toResponsiveImage(hbhrcWZS_),
								}}
								className={"framer-6cybdp"}
								data-framer-name={"icen"}
								layoutDependency={layoutDependency}
								layoutId={"ms_cDnQdJ"}
							/>
						)}
						<RichText
							__fromCanvasComponent={true}
							className={"framer-45g4qb"}
							data-framer-name={"Start 30 day trial"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"TmwqMpfva"}
							style={{
								"--framer-paragraph-spacing": "0px",
								"--variable-reference-t3GkMWijW-c8RabFrxb": t3GkMWijW,
							}}
							text={siRsUxlcm}
							variants={{
								z70rtAAt5: {
									"--extracted-r6o4lv":
										"var(--variable-reference-t3GkMWijW-c8RabFrxb)",
									"--variable-reference-t3GkMWijW-c8RabFrxb": t3GkMWijW,
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									z70rtAAt5: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-da1i8i"}
													data-styles-preset={"ajAJ6qvzK"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--variable-reference-t3GkMWijW-c8RabFrxb))",
													}}
												>
													{"Build better sass website"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-da1i8i"}
									data-styles-preset={"ajAJ6qvzK"}
								>
									{"Build better sass website"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ZS2a7.framer-1fzcipb, .framer-ZS2a7 .framer-1fzcipb { display: block; }",
	".framer-ZS2a7.framer-3hfvhg { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 5px 8px 5px 8px; position: relative; width: min-content; }",
	".framer-ZS2a7 .framer-6cybdp { flex: none; height: 10px; overflow: hidden; position: relative; width: 10px; }",
	".framer-ZS2a7 .framer-45g4qb { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ZS2a7.framer-3hfvhg { gap: 0px; } .framer-ZS2a7.framer-3hfvhg > * { margin: 0px; margin-left: calc(4px / 2); margin-right: calc(4px / 2); } .framer-ZS2a7.framer-3hfvhg > :first-child { margin-left: 0px; } .framer-ZS2a7.framer-3hfvhg > :last-child { margin-right: 0px; } }",
	".framer-ZS2a7.framer-v-8k86l2.framer-3hfvhg { padding: 4px 12px 4px 12px; }",
	...css,
	'.framer-ZS2a7[data-border="true"]::after, .framer-ZS2a7 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerc8RabFrxb = withCSS(Component, css2, "framer-ZS2a7");
var stdin_default = Framerc8RabFrxb;
Framerc8RabFrxb.displayName = "Caption button";
Framerc8RabFrxb.defaultProps = {
	height: 30,
	width: 189,
};
addPropertyControls(Framerc8RabFrxb, {
	variant: {
		options: ["Vbc9dCRFd", "z70rtAAt5"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	siRsUxlcm: {
		defaultValue: "Build better sass website",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	Drur3Isxs: {
		defaultValue: "rgb(255, 255, 255)",
		title: "Background color",
		type: ControlType.Color,
	},
	Ywx6DZQYi: {
		defaultValue: {
			borderColor: "rgba(214, 217, 217, 1)",
			borderStyle: "solid",
			borderWidth: 0.5,
		},
		title: "Border color",
		type: ControlType.Border,
	},
	hbhrcWZS_: {
		__defaultAssetReference:
			"data:framer/asset-reference,MZZ2JdlW7McaVjvNKQqwIxAAbk.svg?originalFilename=Clip+path+group.svg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	Pli8bMfBJ: {
		defaultValue: true,
		title: "Visible",
		type: ControlType.Boolean,
	},
	t3GkMWijW: {
		defaultValue: "rgb(0, 0, 0)",
		title: "Text Color",
		type: ControlType.Color,
	},
});
addFonts(
	Framerc8RabFrxb,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:caption-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Vbc9dCRFd",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CaptionButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var caption_button_default = ComponentWithRoot;
export { caption_button_default as default };
