// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 984c3bea485a0fa6 "Sassku - Creative SaaS and Startup Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Card close' | 'Card open' | 'Phone close' | 'Phone open' // Variant
 * questions?: string // Questions
 * answer?: string // Answer
 * backgroundColor?: string // Background color
}} Props

 */
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-COXHTX6G.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-ISAWCYQO.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-SMK7VFXN.js";
import { className, css, fonts } from "./chunks/chunk-5CVYQU4P.js";
import { routes } from "./chunks/chunk-N7Y33TLT.js";

// virtual:faq-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/t3BQrvoFtR0cw7HLsr52/y5jfY7N1f6jgCxJ0LmQ1/ZnPuizlGD.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["KiRcdJ5dj", "VlkLK_8i4", "hlOMhUW_y", "GbJwgkutf"];
var serializationHash = "framer-QsdbP";
var variantClassNames = {
	GbJwgkutf: "framer-v-1tfhwdd",
	hlOMhUW_y: "framer-v-1odrlmd",
	KiRcdJ5dj: "framer-v-ymvf12",
	VlkLK_8i4: "framer-v-gvfb5",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"Card close": "KiRcdJ5dj",
	"Card open": "VlkLK_8i4",
	"Phone close": "hlOMhUW_y",
	"Phone open": "GbJwgkutf",
};
var getProps = ({
	answer,
	backgroundColor,
	height,
	id,
	questions,
	width,
	...props
}) => {
	var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2, _ref3;
	return {
		...props,
		HwvlrSl9E:
			(_ref =
				questions !== null && questions !== void 0
					? questions
					: props.HwvlrSl9E) !== null && _ref !== void 0
				? _ref
				: "Can I integrate your product with other tools?",
		j5As2kPqV:
			(_ref1 =
				backgroundColor !== null && backgroundColor !== void 0
					? backgroundColor
					: props.j5As2kPqV) !== null && _ref1 !== void 0
				? _ref1
				: "var(--token-c421066d-cdd9-4035-9b52-c69aa0d4f50c, rgb(255, 255, 255))",
		variant:
			(_ref2 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref2 !== void 0
				? _ref2
				: "KiRcdJ5dj",
		yqMPvlVOK:
			(_ref3 =
				answer !== null && answer !== void 0 ? answer : props.yqMPvlVOK) !==
				null && _ref3 !== void 0
				? _ref3
				: 'Incredible work! The team at Deflow transformed our outdated website into a sleek, modern masterpiece. Our site now  performs exceptionally well. Highly recommend their services!"',
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		HwvlrSl9E,
		yqMPvlVOK,
		j5As2kPqV,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureHandlers,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "KiRcdJ5dj",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1cgihuj = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("VlkLK_8i4");
	});
	const onTap5x0ms1 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("KiRcdJ5dj");
	});
	const onTap90lk3o = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("GbJwgkutf");
	});
	const onTap1onoj4s = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("hlOMhUW_y");
	});
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (["VlkLK_8i4", "GbJwgkutf"].includes(baseVariant)) return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className, className4, className3, className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						aria-label={"FAQ Card"}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-ymvf12",
							className5,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Card close"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"KiRcdJ5dj"}
						onTap={onTap1cgihuj}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-24c283da-fb76-4e7c-ad5e-249de576a67f, rgb(224, 225, 255))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							backgroundColor:
								"var(--token-c421066d-cdd9-4035-9b52-c69aa0d4f50c, rgb(255, 255, 255))",
							...style,
						}}
						variants={{
							VlkLK_8i4: {
								backgroundColor: j5As2kPqV,
							},
						}}
						{...addPropertyOverrides(
							{
								GbJwgkutf: {
									"data-framer-name": "Phone open",
									onTap: onTap1onoj4s,
								},
								hlOMhUW_y: {
									"data-framer-name": "Phone close",
									onTap: onTap90lk3o,
								},
								VlkLK_8i4: {
									"data-framer-name": "Card open",
									onTap: onTap5x0ms1,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1062tp3"}
							data-framer-name={"text- icon"}
							layoutDependency={layoutDependency}
							layoutId={"Ap4IFIrca"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1xeitru"}
								data-framer-name={
									"Can I integrate your product with other tools?"
								}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"kGIaLPNv8"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={HwvlrSl9E}
								variants={{
									GbJwgkutf: {
										"--extracted-r6o4lv":
											"var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
									},
									hlOMhUW_y: {
										"--extracted-r6o4lv":
											"var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
									},
									VlkLK_8i4: {
										"--extracted-1lwpl3i":
											"var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										GbJwgkutf: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-vv4slb"}
														data-styles-preset={"bbzL5FwFO"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)))",
														}}
													>
														{"Can I integrate your product with other tools?"}
													</motion.p>
												</React.Fragment>
											),
										},
										hlOMhUW_y: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-vv4slb"}
														data-styles-preset={"bbzL5FwFO"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)))",
														}}
													>
														{"Can I integrate your product with other tools?"}
													</motion.p>
												</React.Fragment>
											),
										},
										VlkLK_8i4: {
											children: (
												<React.Fragment>
													<motion.h5
														className={"framer-styles-preset-1xzgfyq"}
														data-styles-preset={"dnf6oMP66"}
														style={{
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)))",
														}}
													>
														{"Can I integrate your product with other tools?"}
													</motion.h5>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h5
										className={"framer-styles-preset-1xzgfyq"}
										data-styles-preset={"dnf6oMP66"}
									>
										{"Can I integrate your product with other tools?"}
									</motion.h5>
								</React.Fragment>
							</RichText>
							<SVG
								className={"framer-lep7jg"}
								data-framer-name={"chevron-down"}
								fill={"rgba(0,0,0,1)"}
								intrinsicHeight={24}
								intrinsicWidth={24}
								layoutDependency={layoutDependency}
								layoutId={"WYin0Y5XB"}
								style={{
									rotate: 0,
								}}
								svg={
									'<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M6 9L12 15L18 9" stroke="#140A3E" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n'
								}
								variants={{
									GbJwgkutf: {
										rotate: 180,
									},
									hlOMhUW_y: {
										rotate: 360,
									},
									VlkLK_8i4: {
										rotate: 180,
									},
								}}
								withExternalLayout={true}
							/>
						</motion.div>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-4y3ze5"}
								data-framer-name={
									'Incredible work! The team at Deflow transformed our outdated website into a sleek, modern masterpiece. Our site now performs exceptionally well. Highly recommend their services!"'
								}
								fonts={["GF;DM Sans-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"GIXsMKtE_"}
								style={{
									"--extracted-1w3ko1f": "rgba(20, 10, 62, 1)",
									"--framer-paragraph-spacing": "0px",
								}}
								variants={{
									GbJwgkutf: {
										"--extracted-r6o4lv":
											"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
									},
									VlkLK_8i4: {
										"--extracted-r6o4lv":
											"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										GbJwgkutf: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-g3gqkp"}
														data-styles-preset={"QbZRR8GOG"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
														}}
													>
														{
															'Incredible work! The team at Deflow transformed our outdated website into a sleek, modern masterpiece. Our site now  performs exceptionally well. Highly recommend their services!"'
														}
													</motion.p>
												</React.Fragment>
											),
											fonts: ["Inter"],
										},
										VlkLK_8i4: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-e8pqpa"}
														data-styles-preset={"IyWc0A25X"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
														}}
													>
														{
															'Incredible work! The team at Deflow transformed our outdated website into a sleek, modern masterpiece. Our site now  performs exceptionally well. Highly recommend their services!"'
														}
													</motion.p>
												</React.Fragment>
											),
											fonts: ["Inter"],
											text: yqMPvlVOK,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--framer-font-size": "16px",
											"--framer-line-height": "24px",
										}}
									>
										<motion.span
											style={{
												"--font-selector": "R0Y7RE0gU2Fucy1yZWd1bGFy",
												"--framer-font-family": '"DM Sans"',
												"--framer-font-size": "16px",
												"--framer-text-color":
													"var(--extracted-1w3ko1f, rgba(20, 10, 62, 1))",
											}}
										>
											{
												'Incredible work! The team at Deflow transformed our outdated website into a sleek, modern masterpiece. Our site now  performs exceptionally well. Highly recommend their services!"'
											}
										</motion.span>
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QsdbP.framer-ms4thn, .framer-QsdbP .framer-ms4thn { display: block; }",
	".framer-QsdbP.framer-ymvf12 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 20px; position: relative; width: 541px; }",
	".framer-QsdbP .framer-1062tp3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-QsdbP .framer-1xeitru { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-QsdbP .framer-lep7jg { flex: none; height: 24px; position: relative; width: 24px; }",
	".framer-QsdbP .framer-4y3ze5 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-QsdbP.framer-ymvf12, .framer-QsdbP .framer-1062tp3 { gap: 0px; } .framer-QsdbP.framer-ymvf12 > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } .framer-QsdbP.framer-ymvf12 > :first-child { margin-top: 0px; } .framer-QsdbP.framer-ymvf12 > :last-child { margin-bottom: 0px; } .framer-QsdbP .framer-1062tp3 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-QsdbP .framer-1062tp3 > :first-child { margin-left: 0px; } .framer-QsdbP .framer-1062tp3 > :last-child { margin-right: 0px; } }",
	".framer-QsdbP.framer-v-1odrlmd.framer-ymvf12, .framer-QsdbP.framer-v-1tfhwdd.framer-ymvf12 { gap: 8px; padding: 20px 16px 20px 16px; width: 318px; }",
	".framer-QsdbP.framer-v-1odrlmd .framer-1062tp3, .framer-QsdbP.framer-v-1tfhwdd .framer-1062tp3 { align-content: flex-start; align-items: flex-start; }",
	".framer-QsdbP.framer-v-1odrlmd .framer-1xeitru { order: 0; }",
	".framer-QsdbP.framer-v-1odrlmd .framer-lep7jg { height: 20px; order: 1; width: 20px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-QsdbP.framer-v-1odrlmd.framer-ymvf12 { gap: 0px; } .framer-QsdbP.framer-v-1odrlmd.framer-ymvf12 > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-QsdbP.framer-v-1odrlmd.framer-ymvf12 > :first-child { margin-top: 0px; } .framer-QsdbP.framer-v-1odrlmd.framer-ymvf12 > :last-child { margin-bottom: 0px; } }",
	".framer-QsdbP.framer-v-1tfhwdd .framer-lep7jg { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 20px); width: 20px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-QsdbP.framer-v-1tfhwdd.framer-ymvf12 { gap: 0px; } .framer-QsdbP.framer-v-1tfhwdd.framer-ymvf12 > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-QsdbP.framer-v-1tfhwdd.framer-ymvf12 > :first-child { margin-top: 0px; } .framer-QsdbP.framer-v-1tfhwdd.framer-ymvf12 > :last-child { margin-bottom: 0px; } }",
	...css,
	...css4,
	...css3,
	...css2,
	'.framer-QsdbP[data-border="true"]::after, .framer-QsdbP [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerZnPuizlGD = withCSS(Component, css5, "framer-QsdbP");
var stdin_default = FramerZnPuizlGD;
FramerZnPuizlGD.displayName = "FAQ Card";
FramerZnPuizlGD.defaultProps = {
	height: 68,
	width: 541,
};
addPropertyControls(FramerZnPuizlGD, {
	variant: {
		options: ["KiRcdJ5dj", "VlkLK_8i4", "hlOMhUW_y", "GbJwgkutf"],
		optionTitles: ["Card close", "Card open", "Phone close", "Phone open"],
		title: "Variant",
		type: ControlType.Enum,
	},
	HwvlrSl9E: {
		defaultValue: "Can I integrate your product with other tools?",
		displayTextArea: false,
		title: "Questions",
		type: ControlType.String,
	},
	yqMPvlVOK: {
		defaultValue:
			'Incredible work! The team at Deflow transformed our outdated website into a sleek, modern masterpiece. Our site now  performs exceptionally well. Highly recommend their services!"',
		displayTextArea: false,
		title: "Answer",
		type: ControlType.String,
	},
	j5As2kPqV: {
		defaultValue:
			'var(--token-c421066d-cdd9-4035-9b52-c69aa0d4f50c, rgb(255, 255, 255)) /* {"name":"#FFFFFF"} */',
		title: "Background color",
		type: ControlType.Color,
	},
});
addFonts(
	FramerZnPuizlGD,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
				{
					family: "DM Sans",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/dmsans/v15/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAopxhS2f3ZGMZpg.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "GbJwgkutf",
	xl: "KiRcdJ5dj",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var faq_card_default = ComponentWithRoot;
export { faq_card_default as default };
