// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 984c3bea485a0fa6 "Sassku - Creative SaaS and Startup Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * title?: string // Title
 * text?: string // Text
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * textColor?: string //  text Color
 * textColor2?: string // text Color 2
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-L4FPLCQN.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-SMK7VFXN.js";
import { className, css, fonts } from "./chunks/chunk-5CVYQU4P.js";
import { routes } from "./chunks/chunk-N7Y33TLT.js";

// virtual:features-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/3YBPBY56f5nvEBEm3Va9/SPK3j9lDBs5UhUTwB6xV/Vf_l3pCaM.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["d19xOicEY", "PKx0F1gmz", "TOaWYycEz"];
var serializationHash = "framer-xmGbH";
var variantClassNames = {
	d19xOicEY: "framer-v-7k62fh",
	PKx0F1gmz: "framer-v-be3ekk",
	TOaWYycEz: "framer-v-1pyozjv",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "d19xOicEY",
	Phone: "TOaWYycEz",
	Tablet: "PKx0F1gmz",
};
var getProps = ({
	height,
	id,
	image,
	text,
	textColor,
	textColor2,
	title,
	width,
	...props
}) => {
	var _ref,
		_ref1,
		_ref2,
		_humanReadableVariantMap_props_variant,
		_ref3,
		_ref4,
		_ref5;
	return {
		...props,
		ClXNbWmzA:
			(_ref = text !== null && text !== void 0 ? text : props.ClXNbWmzA) !==
				null && _ref !== void 0
				? _ref
				: "Which is the same as sayingthrough shrinking from toil andpain.",
		Gs7oibxHe:
			(_ref1 = title !== null && title !== void 0 ? title : props.Gs7oibxHe) !==
				null && _ref1 !== void 0
				? _ref1
				: "User-Friendly",
		MxPul2cUx:
			(_ref2 = image !== null && image !== void 0 ? image : props.MxPul2cUx) !==
				null && _ref2 !== void 0
				? _ref2
				: {
						src: "https://framerusercontent.com/images/JR0uBUpYXqbxrTzGlYgVEqugU.svg",
					},
		variant:
			(_ref3 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref3 !== void 0
				? _ref3
				: "d19xOicEY",
		VLHrVmUnE:
			(_ref4 =
				textColor2 !== null && textColor2 !== void 0
					? textColor2
					: props.VLHrVmUnE) !== null && _ref4 !== void 0
				? _ref4
				: "var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
		wuvt0DKVf:
			(_ref5 =
				textColor !== null && textColor !== void 0
					? textColor
					: props.wuvt0DKVf) !== null && _ref5 !== void 0
				? _ref5
				: "var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		Gs7oibxHe,
		ClXNbWmzA,
		MxPul2cUx,
		wuvt0DKVf,
		VLHrVmUnE,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureHandlers,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "d19xOicEY",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className3, className, className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						aria-label={"features Card"}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-7k62fh",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"d19xOicEY"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor:
								"var(--token-c421066d-cdd9-4035-9b52-c69aa0d4f50c, rgb(255, 255, 255))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								PKx0F1gmz: {
									"data-framer-name": "Tablet",
								},
								TOaWYycEz: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-73dev"}
							layoutDependency={layoutDependency}
							layoutId={"ViyuNk03x"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									pixelHeight: 48,
									pixelWidth: 48,
									...toResponsiveImage(MxPul2cUx),
								}}
								className={"framer-1vi934e"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"Bit4ro6UG"}
							/>
						</motion.div>
						<motion.div
							className={"framer-1b7f63v"}
							data-framer-name={"Card Content"}
							layoutDependency={layoutDependency}
							layoutId={"wh3ZNtRwN"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-dm5x5a"}
								data-framer-name={"Title"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"lOaqTXhQ3"}
								style={{
									"--extracted-1eung3n":
										"var(--variable-reference-wuvt0DKVf-Vf_l3pCaM)",
									"--framer-paragraph-spacing": "0px",
									"--variable-reference-wuvt0DKVf-Vf_l3pCaM": wuvt0DKVf,
								}}
								text={Gs7oibxHe}
								variants={{
									TOaWYycEz: {
										"--extracted-1lwpl3i":
											"var(--variable-reference-wuvt0DKVf-Vf_l3pCaM)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										TOaWYycEz: {
											children: (
												<React.Fragment>
													<motion.h5
														className={"framer-styles-preset-1xzgfyq"}
														data-styles-preset={"dnf6oMP66"}
														style={{
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--variable-reference-wuvt0DKVf-Vf_l3pCaM))",
														}}
													>
														{"User-Friendly"}
													</motion.h5>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-1c0lwt7"}
										data-styles-preset={"ZrKVS0_J5"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--variable-reference-wuvt0DKVf-Vf_l3pCaM))",
										}}
									>
										{"User-Friendly"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-tsy4nw"}
								data-framer-name={"Subtitle"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"GfVl5nZJV"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-VLHrVmUnE-Vf_l3pCaM)",
									"--framer-paragraph-spacing": "0px",
									"--variable-reference-VLHrVmUnE-Vf_l3pCaM": VLHrVmUnE,
								}}
								text={ClXNbWmzA}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-g3gqkp"}
										data-styles-preset={"QbZRR8GOG"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--variable-reference-VLHrVmUnE-Vf_l3pCaM))",
										}}
									>
										{
											"Which is the same as sayingthrough shrinking from toil andpain."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xmGbH.framer-cazyon, .framer-xmGbH .framer-cazyon { display: block; }",
	".framer-xmGbH.framer-7k62fh { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: flex-start; overflow: visible; padding: 32px; position: relative; width: min-content; }",
	".framer-xmGbH .framer-73dev { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-xmGbH .framer-1vi934e { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 48px; min-width: 48px; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-xmGbH .framer-1b7f63v { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 214px; }",
	".framer-xmGbH .framer-dm5x5a, .framer-xmGbH .framer-tsy4nw { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-xmGbH.framer-7k62fh, .framer-xmGbH .framer-73dev, .framer-xmGbH .framer-1vi934e, .framer-xmGbH .framer-1b7f63v { gap: 0px; } .framer-xmGbH.framer-7k62fh > * { margin: 0px; margin-bottom: calc(36px / 2); margin-top: calc(36px / 2); } .framer-xmGbH.framer-7k62fh > :first-child, .framer-xmGbH .framer-1b7f63v > :first-child { margin-top: 0px; } .framer-xmGbH.framer-7k62fh > :last-child, .framer-xmGbH .framer-1b7f63v > :last-child { margin-bottom: 0px; } .framer-xmGbH .framer-73dev > *, .framer-xmGbH .framer-1vi934e > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-xmGbH .framer-73dev > :first-child, .framer-xmGbH .framer-1vi934e > :first-child { margin-left: 0px; } .framer-xmGbH .framer-73dev > :last-child, .framer-xmGbH .framer-1vi934e > :last-child { margin-right: 0px; } .framer-xmGbH .framer-1b7f63v > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } }",
	".framer-xmGbH.framer-v-be3ekk.framer-7k62fh { gap: 24px; width: 351px; }",
	".framer-xmGbH.framer-v-be3ekk .framer-1b7f63v { width: 287px; }",
	".framer-xmGbH.framer-v-be3ekk .framer-dm5x5a, .framer-xmGbH.framer-v-1pyozjv .framer-dm5x5a { width: 233px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-xmGbH.framer-v-be3ekk.framer-7k62fh { gap: 0px; } .framer-xmGbH.framer-v-be3ekk.framer-7k62fh > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-xmGbH.framer-v-be3ekk.framer-7k62fh > :first-child { margin-top: 0px; } .framer-xmGbH.framer-v-be3ekk.framer-7k62fh > :last-child { margin-bottom: 0px; } }",
	".framer-xmGbH.framer-v-1pyozjv.framer-7k62fh { gap: 24px; padding: 28px; width: 350px; }",
	".framer-xmGbH.framer-v-1pyozjv .framer-1b7f63v { width: 286px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-xmGbH.framer-v-1pyozjv.framer-7k62fh { gap: 0px; } .framer-xmGbH.framer-v-1pyozjv.framer-7k62fh > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-xmGbH.framer-v-1pyozjv.framer-7k62fh > :first-child { margin-top: 0px; } .framer-xmGbH.framer-v-1pyozjv.framer-7k62fh > :last-child { margin-bottom: 0px; } }",
	...css3,
	...css,
	...css2,
];
var FramerVf_l3pCaM = withCSS(Component, css4, "framer-xmGbH");
var stdin_default = FramerVf_l3pCaM;
FramerVf_l3pCaM.displayName = "features Card";
FramerVf_l3pCaM.defaultProps = {
	height: 250,
	width: 278,
};
addPropertyControls(FramerVf_l3pCaM, {
	variant: {
		options: ["d19xOicEY", "PKx0F1gmz", "TOaWYycEz"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Gs7oibxHe: {
		defaultValue: "User-Friendly",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	ClXNbWmzA: {
		defaultValue:
			"Which is the same as sayingthrough shrinking from toil andpain.",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	MxPul2cUx: {
		__defaultAssetReference:
			"data:framer/asset-reference,JR0uBUpYXqbxrTzGlYgVEqugU.svg?originalFilename=group.svg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	wuvt0DKVf: {
		defaultValue:
			"var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
		title: " text Color",
		type: ControlType.Color,
	},
	VLHrVmUnE: {
		defaultValue:
			"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
		title: "text Color 2",
		type: ControlType.Color,
	},
});
addFonts(
	FramerVf_l3pCaM,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:features-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "TOaWYycEz",
	md: "PKx0F1gmz",
	xl: "d19xOicEY",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FeaturesCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var features_card_default = ComponentWithRoot;
export { features_card_default as default };
