// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 984c3bea485a0fa6 "Sassku - Creative SaaS and Startup Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' // Variant
 * title?: string // Title
 * text?: string // Text
 * background?: string // Background
 * titleColor?: string // title Color
 * textColor?: string // Text Color
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * padding?: undefined // Padding
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-L4FPLCQN.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-SMK7VFXN.js";
import { className, css, fonts } from "./chunks/chunk-5CVYQU4P.js";
import { routes } from "./chunks/chunk-N7Y33TLT.js";

// virtual:how-it-s-work-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/iyeZeXyPThQdegpdzvNG/1Gpqt0QFSTDPCzA9crlP/EqX75u_Yo.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["DdDw_ZNxi", "BEjYLHQyA", "oIIeNOtjO"];
var serializationHash = "framer-QPi9h";
var variantClassNames = {
	BEjYLHQyA: "framer-v-6ettt7",
	DdDw_ZNxi: "framer-v-1srir0w",
	oIIeNOtjO: "framer-v-iqz834",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var numberToPixelString = (value) => {
	if (typeof value !== "number") return value;
	if (!Number.isFinite(value)) return void 0;
	return Math.max(0, value) + "px";
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 50,
};
var transition1 = {
	damping: 30,
	delay: 0.2,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 50,
};
var transition2 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "DdDw_ZNxi",
	"Variant 2": "BEjYLHQyA",
	"Variant 3": "oIIeNOtjO",
};
var getProps = ({
	background,
	height,
	id,
	image,
	padding,
	text,
	textColor,
	title,
	titleColor,
	width,
	...props
}) => {
	var _ref,
		_ref1,
		_ref2,
		_ref3,
		_humanReadableVariantMap_props_variant,
		_ref4,
		_ref5,
		_ref6,
		_ref7;
	return {
		...props,
		A8LLEHKOz:
			(_ref =
				padding !== null && padding !== void 0 ? padding : props.A8LLEHKOz) !==
				null && _ref !== void 0
				? _ref
				: "0px",
		bkiS1W6hS:
			(_ref1 = title !== null && title !== void 0 ? title : props.bkiS1W6hS) !==
				null && _ref1 !== void 0
				? _ref1
				: "Sign up",
		JLFzzKZ3u:
			(_ref2 = text !== null && text !== void 0 ? text : props.JLFzzKZ3u) !==
				null && _ref2 !== void 0
				? _ref2
				: "Behold upon Him God a creature fruitful Fly That seasons tree Isn't fruit also lesser brought.",
		T2JKVeut2:
			(_ref3 =
				background !== null && background !== void 0
					? background
					: props.T2JKVeut2) !== null && _ref3 !== void 0
				? _ref3
				: "rgb(255, 255, 255)",
		variant:
			(_ref4 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref4 !== void 0
				? _ref4
				: "DdDw_ZNxi",
		VkwphK_am:
			(_ref5 =
				textColor !== null && textColor !== void 0
					? textColor
					: props.VkwphK_am) !== null && _ref5 !== void 0
				? _ref5
				: "var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
		WP7dPYZhq:
			(_ref6 =
				titleColor !== null && titleColor !== void 0
					? titleColor
					: props.WP7dPYZhq) !== null && _ref6 !== void 0
				? _ref6
				: "var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
		ZQr5jGQna:
			(_ref7 = image !== null && image !== void 0 ? image : props.ZQr5jGQna) !==
				null && _ref7 !== void 0
				? _ref7
				: {
						src: "https://framerusercontent.com/images/ypkZghFcwa2Yxx4tMVJW2O3YkY.svg",
					},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		bkiS1W6hS,
		JLFzzKZ3u,
		T2JKVeut2,
		WP7dPYZhq,
		VkwphK_am,
		ZQr5jGQna,
		A8LLEHKOz,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureHandlers,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "DdDw_ZNxi",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className3, className, className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__exit={animation1}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1srir0w",
							className4,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"DdDw_ZNxi"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--1m1pgbx": numberToPixelString(A8LLEHKOz),
							...style,
						}}
						{...addPropertyOverrides(
							{
								BEjYLHQyA: {
									"data-framer-name": "Variant 2",
								},
								oIIeNOtjO: {
									"data-framer-name": "Variant 3",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1hc6tpp"}
							data-framer-name={"Card Content Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"gH9lqDGlK"}
							style={{
								backgroundColor: T2JKVeut2,
							}}
						>
							<motion.div
								className={"framer-akt641"}
								data-framer-name={"Card Content"}
								layoutDependency={layoutDependency}
								layoutId={"k6vHth_kU"}
							>
								<motion.div
									className={"framer-1oak8e3"}
									data-framer-name={"Text"}
									layoutDependency={layoutDependency}
									layoutId={"rKTLHJEqb"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1ldmesb"}
										data-framer-name={"Title"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"nh6YrGK_a"}
										style={{
											"--extracted-1eung3n":
												"var(--variable-reference-WP7dPYZhq-EqX75u_Yo)",
											"--framer-paragraph-spacing": "0px",
											"--variable-reference-WP7dPYZhq-EqX75u_Yo": WP7dPYZhq,
										}}
										text={bkiS1W6hS}
										variants={{
											BEjYLHQyA: {
												"--extracted-1lwpl3i":
													"var(--variable-reference-WP7dPYZhq-EqX75u_Yo)",
											},
											oIIeNOtjO: {
												"--extracted-1lwpl3i":
													"var(--variable-reference-WP7dPYZhq-EqX75u_Yo)",
											},
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												BEjYLHQyA: {
													children: (
														<React.Fragment>
															<motion.h5
																className={"framer-styles-preset-1xzgfyq"}
																data-styles-preset={"dnf6oMP66"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-1lwpl3i, var(--variable-reference-WP7dPYZhq-EqX75u_Yo))",
																}}
															>
																{"Sign up"}
															</motion.h5>
														</React.Fragment>
													),
												},
												oIIeNOtjO: {
													children: (
														<React.Fragment>
															<motion.h5
																className={"framer-styles-preset-1xzgfyq"}
																data-styles-preset={"dnf6oMP66"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-1lwpl3i, var(--variable-reference-WP7dPYZhq-EqX75u_Yo))",
																}}
															>
																{"Sign up"}
															</motion.h5>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.h4
												className={"framer-styles-preset-1c0lwt7"}
												data-styles-preset={"ZrKVS0_J5"}
												style={{
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--variable-reference-WP7dPYZhq-EqX75u_Yo))",
												}}
											>
												{"Sign up"}
											</motion.h4>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-q8sg7j"}
										data-framer-name={"Subtitle"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"gMHq46s9l"}
										style={{
											"--extracted-r6o4lv":
												"var(--variable-reference-VkwphK_am-EqX75u_Yo)",
											"--framer-paragraph-spacing": "0px",
											"--variable-reference-VkwphK_am-EqX75u_Yo": VkwphK_am,
										}}
										text={JLFzzKZ3u}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-g3gqkp"}
												data-styles-preset={"QbZRR8GOG"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--variable-reference-VkwphK_am-EqX75u_Yo))",
												}}
											>
												{
													"Behold upon Him God a creature fruitful Fly That seasons tree Isn't fruit also lesser brought."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<Image
									background={{
										alt: "",
										fit: "fill",
										pixelHeight: 40,
										pixelWidth: 40,
										sizes: "40px",
										...toResponsiveImage(ZQr5jGQna),
									}}
									className={"framer-d6ax1u"}
									layoutDependency={layoutDependency}
									layoutId={"BWVFcDo4f"}
									{...addPropertyOverrides(
										{
											BEjYLHQyA: {
												background: {
													alt: "",
													fit: "fill",
													pixelHeight: 40,
													pixelWidth: 40,
													sizes: "24px",
													...toResponsiveImage(ZQr5jGQna),
												},
											},
											oIIeNOtjO: {
												background: {
													alt: "",
													fit: "fill",
													pixelHeight: 40,
													pixelWidth: 40,
													sizes: "24px",
													...toResponsiveImage(ZQr5jGQna),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.div>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QPi9h.framer-19ubw6v, .framer-QPi9h .framer-19ubw6v { display: block; }",
	".framer-QPi9h.framer-1srir0w { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: var(--1m1pgbx); position: relative; width: 375px; }",
	".framer-QPi9h .framer-1hc6tpp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 24px; position: relative; width: 100%; }",
	".framer-QPi9h .framer-akt641 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-QPi9h .framer-1oak8e3 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-QPi9h .framer-1ldmesb, .framer-QPi9h .framer-q8sg7j { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-QPi9h .framer-d6ax1u { flex: none; height: 40px; overflow: hidden; position: relative; width: 40px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-QPi9h.framer-1srir0w, .framer-QPi9h .framer-1hc6tpp, .framer-QPi9h .framer-akt641, .framer-QPi9h .framer-1oak8e3 { gap: 0px; } .framer-QPi9h.framer-1srir0w > *, .framer-QPi9h .framer-1oak8e3 > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-QPi9h.framer-1srir0w > :first-child, .framer-QPi9h .framer-1hc6tpp > :first-child, .framer-QPi9h .framer-1oak8e3 > :first-child { margin-top: 0px; } .framer-QPi9h.framer-1srir0w > :last-child, .framer-QPi9h .framer-1hc6tpp > :last-child, .framer-QPi9h .framer-1oak8e3 > :last-child { margin-bottom: 0px; } .framer-QPi9h .framer-1hc6tpp > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-QPi9h .framer-akt641 > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-QPi9h .framer-akt641 > :first-child { margin-left: 0px; } .framer-QPi9h .framer-akt641 > :last-child { margin-right: 0px; } }",
	".framer-QPi9h.framer-v-6ettt7.framer-1srir0w { gap: 12px; width: 230px; }",
	".framer-QPi9h.framer-v-6ettt7 .framer-1hc6tpp, .framer-QPi9h.framer-v-iqz834 .framer-1hc6tpp { padding: 20px 16px 20px 16px; }",
	".framer-QPi9h.framer-v-6ettt7 .framer-1oak8e3, .framer-QPi9h.framer-v-iqz834 .framer-1oak8e3 { gap: 8px; }",
	".framer-QPi9h.framer-v-6ettt7 .framer-d6ax1u, .framer-QPi9h.framer-v-iqz834 .framer-d6ax1u { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 24px); width: 24px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-QPi9h.framer-v-6ettt7.framer-1srir0w, .framer-QPi9h.framer-v-6ettt7 .framer-1oak8e3 { gap: 0px; } .framer-QPi9h.framer-v-6ettt7.framer-1srir0w > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } .framer-QPi9h.framer-v-6ettt7.framer-1srir0w > :first-child, .framer-QPi9h.framer-v-6ettt7 .framer-1oak8e3 > :first-child { margin-top: 0px; } .framer-QPi9h.framer-v-6ettt7.framer-1srir0w > :last-child, .framer-QPi9h.framer-v-6ettt7 .framer-1oak8e3 > :last-child { margin-bottom: 0px; } .framer-QPi9h.framer-v-6ettt7 .framer-1oak8e3 > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } }",
	".framer-QPi9h.framer-v-iqz834.framer-1srir0w { gap: 12px; width: 350px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-QPi9h.framer-v-iqz834.framer-1srir0w, .framer-QPi9h.framer-v-iqz834 .framer-1oak8e3 { gap: 0px; } .framer-QPi9h.framer-v-iqz834.framer-1srir0w > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } .framer-QPi9h.framer-v-iqz834.framer-1srir0w > :first-child, .framer-QPi9h.framer-v-iqz834 .framer-1oak8e3 > :first-child { margin-top: 0px; } .framer-QPi9h.framer-v-iqz834.framer-1srir0w > :last-child, .framer-QPi9h.framer-v-iqz834 .framer-1oak8e3 > :last-child { margin-bottom: 0px; } .framer-QPi9h.framer-v-iqz834 .framer-1oak8e3 > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } }",
	...css3,
	...css,
	...css2,
];
var FramerEqX75u_Yo = withCSS(Component, css4, "framer-QPi9h");
var stdin_default = FramerEqX75u_Yo;
FramerEqX75u_Yo.displayName = "How it\u2019s work Card";
FramerEqX75u_Yo.defaultProps = {
	height: 154,
	width: 375,
};
addPropertyControls(FramerEqX75u_Yo, {
	variant: {
		options: ["DdDw_ZNxi", "BEjYLHQyA", "oIIeNOtjO"],
		optionTitles: ["Variant 1", "Variant 2", "Variant 3"],
		title: "Variant",
		type: ControlType.Enum,
	},
	bkiS1W6hS: {
		defaultValue: "Sign up",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	JLFzzKZ3u: {
		defaultValue:
			"Behold upon Him God a creature fruitful Fly That seasons tree Isn't fruit also lesser brought.",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	T2JKVeut2: {
		defaultValue: "rgb(255, 255, 255)",
		title: "Background",
		type: ControlType.Color,
	},
	WP7dPYZhq: {
		defaultValue:
			"var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
		title: "title Color",
		type: ControlType.Color,
	},
	VkwphK_am: {
		defaultValue:
			"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
		title: "Text Color",
		type: ControlType.Color,
	},
	ZQr5jGQna: {
		__defaultAssetReference:
			"data:framer/asset-reference,ypkZghFcwa2Yxx4tMVJW2O3YkY.svg?originalFilename=mdi_account-key.svg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	A8LLEHKOz: {
		defaultValue: "0px",
		title: "Padding",
		type: ControlType.Padding,
	},
});
addFonts(
	FramerEqX75u_Yo,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:how-it-s-work-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "oIIeNOtjO",
	md: "BEjYLHQyA",
	xl: "DdDw_ZNxi",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HowItSWorkCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var how_it_s_work_card_default = ComponentWithRoot;
export { how_it_s_work_card_default as default };
