// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 984c3bea485a0fa6 "Sassku - Creative SaaS and Startup Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Tablet open' | 'Phone' | 'Phone open' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-N7S7DP3D.js";
import "./chunks/chunk-3UHWVJNE.js";
import { routes } from "./chunks/chunk-N7Y33TLT.js";

// virtual:nav
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/9B8jJWhWykok956nvIov/c1eQdJCY2wLZgcTs2PLn/QDDR7pqyK.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/gCWYDaqEQJC4nebs6IFe/Btz2p2VeZ2JqgBy69Q6L/AV5lDhBeu.js
import { fontStore } from "unframer";
fontStore.loadFonts([]);
var fonts = [
	{
		explicitInter: true,
		fonts: [],
	},
];
var css = [
	'.framer-Nyu0A .framer-styles-preset-1wxyf0f:not(.rich-text-wrapper), .framer-Nyu0A .framer-styles-preset-1wxyf0f.rich-text-wrapper a { --framer-link-current-text-color: var(--token-e8d100af-0acb-4538-a574-19ca78616225, #8277ff) /* {"name":"#8277FF"} */; --framer-link-current-text-decoration: underline; --framer-link-hover-text-color: var(--token-e8d100af-0acb-4538-a574-19ca78616225, #8277ff) /* {"name":"#8277FF"} */; --framer-link-hover-text-decoration: underline; --framer-link-text-color: var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, #140a3e); --framer-link-text-decoration: none; }',
];
var className = "framer-Nyu0A";

// /:https://framerusercontent.com/modules/kLzsBz4hPeXEl4f7WdyY/uZQHenVjphgMwXNf75le/QbZRR8GOG.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"GF;DM Sans-regular",
	"GF;DM Sans-700",
	"GF;DM Sans-700italic",
	"GF;DM Sans-italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "DM Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAopxhS2f3ZGMZpg.woff2",
				weight: "400",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwARZthS2f3ZGMZpg.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat9uCm32RmYJpso5.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat-JDW32RmYJpso5.woff2",
				weight: "400",
			},
		],
	},
];
var css2 = [
	'.framer-ILzdQ .framer-styles-preset-g3gqkp:not(.rich-text-wrapper), .framer-ILzdQ .framer-styles-preset-g3gqkp.rich-text-wrapper p { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 20px; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: #333333; --framer-text-decoration: none; --framer-text-transform: none; }',
];
var className2 = "framer-ILzdQ";

// /:https://framerusercontent.com/modules/9B8jJWhWykok956nvIov/c1eQdJCY2wLZgcTs2PLn/QDDR7pqyK.js
var ButtonFonts = getFonts(stdin_default);
var cycleOrder = [
	"emEdLZwHG",
	"NvFg_SNXZ",
	"wh6wZzT4e",
	"C2MKqmkz4",
	"bWAFpMR8m",
];
var serializationHash = "framer-OueQb";
var variantClassNames = {
	bWAFpMR8m: "framer-v-nqv0r",
	C2MKqmkz4: "framer-v-vooqzl",
	emEdLZwHG: "framer-v-9322as",
	NvFg_SNXZ: "framer-v-169ag3r",
	wh6wZzT4e: "framer-v-k7rcim",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Phone open": "bWAFpMR8m",
	"Tablet open": "wh6wZzT4e",
	Desktop: "emEdLZwHG",
	Phone: "C2MKqmkz4",
	Tablet: "NvFg_SNXZ",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "emEdLZwHG",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "emEdLZwHG",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap3hw68w = activeVariantCallback(async (...args) => {
		setVariant("emEdLZwHG");
	});
	const onTapfb1wul = activeVariantCallback(async (...args) => {
		setVariant("ohYhgII4P");
	});
	const onTap1bxj4ni = activeVariantCallback(async (...args) => {
		setVariant("wh6wZzT4e");
	});
	const onTapxoxbkp = activeVariantCallback(async (...args) => {
		setVariant("bWAFpMR8m");
	});
	const onTapv1nx2s = activeVariantCallback(async (...args) => {
		setVariant("WuIhRbSyl");
	});
	const onTapb2sfkb = activeVariantCallback(async (...args) => {
		setVariant("NvFg_SNXZ");
	});
	const onTap1qp0t9u = activeVariantCallback(async (...args) => {
		setVariant("C2MKqmkz4");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["NvFg_SNXZ", "C2MKqmkz4"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["wh6wZzT4e", "bWAFpMR8m"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (["C2MKqmkz4", "bWAFpMR8m"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed3 = () => {
		if (["NvFg_SNXZ", "wh6wZzT4e"].includes(baseVariant)) return false;
		return true;
	};
	const router = useRouter();
	const isDisplayed4 = () => {
		if (baseVariant === "bWAFpMR8m") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.nav
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-9322as",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"emEdLZwHG"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								bWAFpMR8m: {
									"data-framer-name": "Phone open",
								},
								C2MKqmkz4: {
									"data-framer-name": "Phone",
								},
								NvFg_SNXZ: {
									"data-framer-name": "Tablet",
								},
								wh6wZzT4e: {
									"data-framer-name": "Tablet open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-22pcp"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"KBUlmzYUe"}
						>
							<Link
								href={{
									webPageId: "augiA20Il",
								}}
								motionChild={true}
								nodeId={"vkCelapEh"}
								scopeId={"QDDR7pqyK"}
							>
								<motion.a
									aria-label={"SaaSKU Logo"}
									className={"framer-iiwkxi framer-16b58vx"}
									data-framer-name={"SaaSKU Logo"}
									layoutDependency={layoutDependency}
									layoutId={"vkCelapEh"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-l3x1g7"}
										data-highlight={true}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"E9Iyoj8Fr"}
										onTap={onTap3hw68w}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												dir={"auto"}
												style={{
													"--framer-text-alignment": "center",
												}}
											>
												{"SmartJob"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.a>
							</Link>
							{isDisplayed() && (
								<motion.div
									className={"framer-whm0ht"}
									data-framer-name={"menu"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"hdAAK7LBI"}
									onTap={onTapfb1wul}
									style={{
										background:
											"linear-gradient(180deg, var(--token-e8d100af-0acb-4538-a574-19ca78616225, rgb(130, 119, 255)) 0%, var(--token-cdb83f14-5d25-4ea9-860e-c99b1c747d6c, rgb(119, 255, 181)) 100%)",
									}}
									variants={{
										C2MKqmkz4: {
											background:
												"linear-gradient(180deg, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)) 0%, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)) 100%)",
										},
										NvFg_SNXZ: {
											background:
												"linear-gradient(180deg, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)) 0%, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)) 100%)",
										},
									}}
									{...addPropertyOverrides(
										{
											C2MKqmkz4: {
												onTap: onTapxoxbkp,
											},
											NvFg_SNXZ: {
												onTap: onTap1bxj4ni,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SVG
										className={"framer-1yygam7"}
										data-framer-name={"menu"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"AVf4riuS5"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><path d="M 3 12 L 21 12" fill="transparent" stroke-width="2" stroke="rgb(255,255,255)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path><path d="M 3 6 L 21 6" fill="transparent" stroke-width="2" stroke="rgb(255,255,255)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path><path d="M 3 18 L 21 18" fill="transparent" stroke-width="2" stroke="rgb(255,255,255)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
										}
										svgContentId={9692911541}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												NvFg_SNXZ: {
													svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 2.5 10 L 17.5 10" fill="transparent" stroke-width="1.67" stroke="rgb(255,255,255)" stroke-linecap="round" stroke-linejoin="round"></path><path d="M 2.5 5 L 17.5 5" fill="transparent" stroke-width="1.67" stroke="rgb(255,255,255)" stroke-linecap="round" stroke-linejoin="round"></path><path d="M 2.5 15 L 17.5 15" fill="transparent" stroke-width="1.67" stroke="rgb(255,255,255)" stroke-linecap="round" stroke-linejoin="round"></path></svg>',
													svgContentId: 9470916412,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							)}
							{isDisplayed1() && (
								<motion.div
									className={"framer-zgafj8"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"NcAFxpmhM"}
									onTap={onTapv1nx2s}
									style={{
										background:
											"linear-gradient(180deg, var(--token-e8d100af-0acb-4538-a574-19ca78616225, rgb(130, 119, 255)) 0%, var(--token-cdb83f14-5d25-4ea9-860e-c99b1c747d6c, rgb(119, 255, 181)) 100%)",
									}}
									variants={{
										bWAFpMR8m: {
											background:
												"linear-gradient(180deg, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)) 0%, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)) 100%)",
										},
										wh6wZzT4e: {
											background:
												"linear-gradient(180deg, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)) 0%, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)) 100%)",
										},
									}}
									{...addPropertyOverrides(
										{
											bWAFpMR8m: {
												onTap: onTap1qp0t9u,
											},
											wh6wZzT4e: {
												onTap: onTapb2sfkb,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SVG
										className={"framer-f7gwlk"}
										data-framer-name={"menu"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"S7MVQiIca"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><path d="M 0 0 L 18 0" transform="translate(3 12) rotate(-45 9 0.5)" fill="var(--token-349cd685-fc87-482d-a725-628802c214de, rgb(230, 224, 238)) /* {&quot;name&quot;:&quot;Main 2&quot;} */" stroke-width="2" stroke="rgb(255,255,255)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path><path d="M 0 0 L 18 0" transform="translate(3 12) rotate(45 9 0.5)" fill="var(--token-349cd685-fc87-482d-a725-628802c214de, rgb(230, 224, 238)) /* {&quot;name&quot;:&quot;Main 2&quot;} */" stroke-width="2" stroke="rgb(255,255,255)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
										}
										svgContentId={12331262857}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												wh6wZzT4e: {
													svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 0 0 L 15 0" transform="translate(2.559 9.976) rotate(-45 7.5 0.5)" fill="var(--token-349cd685-fc87-482d-a725-628802c214de, rgb(230, 224, 238)) /* {&quot;name&quot;:&quot;Main 2&quot;} */" stroke-width="1.67" stroke="rgb(255,255,255)" stroke-linecap="round" stroke-linejoin="round"></path><path d="M 0 0 L 15 0" transform="translate(2.441 9.976) rotate(45 7.5 0.5)" fill="var(--token-349cd685-fc87-482d-a725-628802c214de, rgb(230, 224, 238)) /* {&quot;name&quot;:&quot;Main 2&quot;} */" stroke-width="1.67" stroke="rgb(255,255,255)" stroke-linecap="round" stroke-linejoin="round"></path></svg>',
													svgContentId: 9607320581,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							)}
							{isDisplayed2() && (
								<motion.div
									className={"framer-byswrc"}
									data-framer-name={"Nav Button Wrap"}
									layoutDependency={layoutDependency}
									layoutId={"TQUNlpy_M"}
								>
									{isDisplayed3() && (
										<motion.div
											className={"framer-1lc1t5b"}
											data-framer-name={"Nav Menu"}
											layoutDependency={layoutDependency}
											layoutId={"zItFuCvpB"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1fvsp4b"}
												data-framer-name={"Home"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"AG1MYdm0j"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-g3gqkp"}
														data-styles-preset={"QbZRR8GOG"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
														}}
													>
														<Link
															href={{
																webPageId: "augiA20Il",
															}}
															motionChild={true}
															nodeId={"AG1MYdm0j"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"QDDR7pqyK"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1wxyf0f"}
																data-styles-preset={"AV5lDhBeu"}
															>
																{"Home"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-65i2v0"}
												data-framer-name={"About Us"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"BzxHRTG7C"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-g3gqkp"}
														data-styles-preset={"QbZRR8GOG"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
														}}
													>
														<Link
															href={{
																webPageId: "E_UpwbG0Z",
															}}
															motionChild={true}
															nodeId={"BzxHRTG7C"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"QDDR7pqyK"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1wxyf0f"}
																data-styles-preset={"AV5lDhBeu"}
															>
																{"About Us"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-affud3"}
												data-framer-name={"Services"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"U2O0JUd9j"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-g3gqkp"}
														data-styles-preset={"QbZRR8GOG"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
														}}
													>
														<Link
															href={{
																webPageId: "f91ELPPbj",
															}}
															motionChild={true}
															nodeId={"U2O0JUd9j"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"QDDR7pqyK"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1wxyf0f"}
																data-styles-preset={"AV5lDhBeu"}
															>
																{"Services"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-frghuw"}
												data-framer-name={"Pricing"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"AyN2VaHdW"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-g3gqkp"}
														data-styles-preset={"QbZRR8GOG"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
														}}
													>
														<Link
															href={{
																webPageId: "xxSRWhFxR",
															}}
															motionChild={true}
															nodeId={"AyN2VaHdW"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"QDDR7pqyK"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1wxyf0f"}
																data-styles-preset={"AV5lDhBeu"}
															>
																{"Pricing"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-4v87py"}
												data-framer-name={"Features"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"DhKInLcsY"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-g3gqkp"}
														data-styles-preset={"QbZRR8GOG"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
														}}
													>
														<Link
															href={{
																webPageId: "RAClwn4sg",
															}}
															motionChild={true}
															nodeId={"DhKInLcsY"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"QDDR7pqyK"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1wxyf0f"}
																data-styles-preset={"AV5lDhBeu"}
															>
																{"Features"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-frbvgx"}
												data-framer-name={"Blog"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"msOyP2lAh"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-g3gqkp"}
														data-styles-preset={"QbZRR8GOG"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
														}}
													>
														<Link
															href={{
																webPageId: "bHQyWbA6V",
															}}
															motionChild={true}
															nodeId={"msOyP2lAh"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"QDDR7pqyK"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1wxyf0f"}
																data-styles-preset={"AV5lDhBeu"}
															>
																{"Blog"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1e14bh0"}
												data-framer-name={"Contact Us"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"Q0XAW4tPr"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-g3gqkp"}
														data-styles-preset={"QbZRR8GOG"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
														}}
													>
														<Link
															href={{
																webPageId: "KAJVgh9jx",
															}}
															motionChild={true}
															nodeId={"Q0XAW4tPr"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"QDDR7pqyK"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1wxyf0f"}
																data-styles-preset={"AV5lDhBeu"}
															>
																{"Contact Us"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									)}
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "KAJVgh9jx",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "KAJVgh9jx",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "KAJVgh9jx",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												height={44}
												y={
													(componentViewport?.y || 0) +
													(16 +
														((componentViewport?.height || 68) - 32 - 44) / 2) +
													0 +
													0
												}
												{...addPropertyOverrides(
													{
														NvFg_SNXZ: {
															y:
																(componentViewport?.y || 0) +
																12 +
																(((componentViewport?.height || 60) - 24 - 44) /
																	2 +
																	0 +
																	0) +
																0 +
																0,
														},
														wh6wZzT4e: {
															y:
																(componentViewport?.y || 0) +
																12 +
																(((componentViewport?.height || 368) -
																	24 -
																	352) /
																	2 +
																	0 +
																	0) +
																0 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-jevznv-container"}
													layoutDependency={layoutDependency}
													layoutId={"ZJnPQ44MN-container"}
													nodeId={"ZJnPQ44MN"}
													rendersWithMotion={true}
													scopeId={"QDDR7pqyK"}
												>
													{_jsx(stdin_default, {
														height: "100%",
														id: "ZJnPQ44MN",
														layoutId: "ZJnPQ44MN",
														rfFF_d5OS: "Get early access",
														RLoqfFjRC: resolvedLinks[0],
														variant: matchVariant("e8dVm4yJw"),
														width: "100%",
														zjfJ_dvfV: false,
														...addPropertyOverrides(
															{
																NvFg_SNXZ: {
																	RLoqfFjRC: resolvedLinks[1],
																},
																wh6wZzT4e: {
																	RLoqfFjRC: resolvedLinks[2],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</motion.div>
							)}
						</motion.div>
						{isDisplayed1() && (
							<motion.div
								className={"framer-1t4hj1s"}
								data-framer-name={"Frame 2"}
								layoutDependency={layoutDependency}
								layoutId={"mzT9rfcXo"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-18n70lh"}
									data-framer-name={"Home"}
									fonts={["GF;DM Sans-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"xSAxPIJTh"}
									style={{
										"--extracted-1w3ko1f": "rgba(20, 10, 62, 1)",
										"--framer-paragraph-spacing": "0px",
									}}
									variants={{
										bWAFpMR8m: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
										wh6wZzT4e: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											bWAFpMR8m: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "augiA20Il",
																}}
																motionChild={true}
																nodeId={"xSAxPIJTh"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"Home"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
											wh6wZzT4e: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "augiA20Il",
																}}
																motionChild={true}
																nodeId={"xSAxPIJTh"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"Home"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--framer-font-size": "14px",
												"--framer-line-height": "20px",
											}}
										>
											<motion.span
												style={{
													"--font-selector": "R0Y7RE0gU2Fucy1yZWd1bGFy",
													"--framer-font-family": '"DM Sans"',
													"--framer-font-size": "14px",
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-color":
														"var(--extracted-1w3ko1f, rgba(20, 10, 62, 1))",
												}}
											>
												{"Home"}
											</motion.span>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-72auvo"}
									data-framer-name={"About Us"}
									fonts={["GF;DM Sans-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"uiuiqWLBG"}
									style={{
										"--extracted-1w3ko1f": "rgba(20, 10, 62, 1)",
										"--framer-paragraph-spacing": "0px",
									}}
									variants={{
										bWAFpMR8m: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
										wh6wZzT4e: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											bWAFpMR8m: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "E_UpwbG0Z",
																}}
																motionChild={true}
																nodeId={"uiuiqWLBG"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"About Us"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
											wh6wZzT4e: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "E_UpwbG0Z",
																}}
																motionChild={true}
																nodeId={"uiuiqWLBG"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"About Us"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--framer-font-size": "14px",
												"--framer-line-height": "20px",
											}}
										>
											<motion.span
												style={{
													"--font-selector": "R0Y7RE0gU2Fucy1yZWd1bGFy",
													"--framer-font-family": '"DM Sans"',
													"--framer-font-size": "14px",
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-color":
														"var(--extracted-1w3ko1f, rgba(20, 10, 62, 1))",
												}}
											>
												{"About Us"}
											</motion.span>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-9o6uvw"}
									data-framer-name={"Services"}
									fonts={["GF;DM Sans-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"qrz5g1ShO"}
									style={{
										"--extracted-1w3ko1f": "rgba(20, 10, 62, 1)",
										"--framer-paragraph-spacing": "0px",
									}}
									variants={{
										bWAFpMR8m: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
										wh6wZzT4e: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											bWAFpMR8m: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "f91ELPPbj",
																}}
																motionChild={true}
																nodeId={"qrz5g1ShO"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"Services"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
											wh6wZzT4e: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "f91ELPPbj",
																}}
																motionChild={true}
																nodeId={"qrz5g1ShO"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"Services"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--framer-font-size": "14px",
												"--framer-line-height": "20px",
											}}
										>
											<motion.span
												style={{
													"--font-selector": "R0Y7RE0gU2Fucy1yZWd1bGFy",
													"--framer-font-family": '"DM Sans"',
													"--framer-font-size": "14px",
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-color":
														"var(--extracted-1w3ko1f, rgba(20, 10, 62, 1))",
												}}
											>
												{"Services"}
											</motion.span>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1leoh9"}
									data-framer-name={"Pricing"}
									fonts={["GF;DM Sans-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"ywJbC5hMA"}
									style={{
										"--extracted-1w3ko1f": "rgba(20, 10, 62, 1)",
										"--framer-paragraph-spacing": "0px",
									}}
									variants={{
										bWAFpMR8m: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
										wh6wZzT4e: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											bWAFpMR8m: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "xxSRWhFxR",
																}}
																motionChild={true}
																nodeId={"ywJbC5hMA"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"Pricing"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
											wh6wZzT4e: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "ZN4mcuvzr",
																}}
																motionChild={true}
																nodeId={"ywJbC5hMA"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"Pricing"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--framer-font-size": "14px",
												"--framer-line-height": "20px",
											}}
										>
											<motion.span
												style={{
													"--font-selector": "R0Y7RE0gU2Fucy1yZWd1bGFy",
													"--framer-font-family": '"DM Sans"',
													"--framer-font-size": "14px",
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-color":
														"var(--extracted-1w3ko1f, rgba(20, 10, 62, 1))",
												}}
											>
												{"Pricing"}
											</motion.span>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1iplzx9"}
									data-framer-name={"Features"}
									fonts={["GF;DM Sans-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"Jf81qOayf"}
									style={{
										"--extracted-1w3ko1f": "rgba(20, 10, 62, 1)",
										"--framer-paragraph-spacing": "0px",
									}}
									variants={{
										bWAFpMR8m: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
										wh6wZzT4e: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											bWAFpMR8m: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "RAClwn4sg",
																}}
																motionChild={true}
																nodeId={"Jf81qOayf"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"Features"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
											wh6wZzT4e: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "eMmTsgsD7",
																}}
																motionChild={true}
																nodeId={"Jf81qOayf"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"Features"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--framer-font-size": "14px",
												"--framer-line-height": "20px",
											}}
										>
											<motion.span
												style={{
													"--font-selector": "R0Y7RE0gU2Fucy1yZWd1bGFy",
													"--framer-font-family": '"DM Sans"',
													"--framer-font-size": "14px",
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-color":
														"var(--extracted-1w3ko1f, rgba(20, 10, 62, 1))",
												}}
											>
												{"Features"}
											</motion.span>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-y0hys9"}
									data-framer-name={"Blog"}
									fonts={["GF;DM Sans-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"YlPK5mxJb"}
									style={{
										"--extracted-1w3ko1f": "rgba(20, 10, 62, 1)",
										"--framer-paragraph-spacing": "0px",
									}}
									variants={{
										bWAFpMR8m: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
										wh6wZzT4e: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											bWAFpMR8m: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "bHQyWbA6V",
																}}
																motionChild={true}
																nodeId={"YlPK5mxJb"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"Blog"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
											wh6wZzT4e: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "bHQyWbA6V",
																}}
																motionChild={true}
																nodeId={"YlPK5mxJb"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"Blog"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--framer-font-size": "14px",
												"--framer-line-height": "20px",
											}}
										>
											<motion.span
												style={{
													"--font-selector": "R0Y7RE0gU2Fucy1yZWd1bGFy",
													"--framer-font-family": '"DM Sans"',
													"--framer-font-size": "14px",
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-color":
														"var(--extracted-1w3ko1f, rgba(20, 10, 62, 1))",
												}}
											>
												{"Blog"}
											</motion.span>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-fx8xlo"}
									data-framer-name={"Contact Us"}
									fonts={["GF;DM Sans-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"oZTUMtXwZ"}
									style={{
										"--extracted-1w3ko1f": "rgba(20, 10, 62, 1)",
										"--framer-paragraph-spacing": "0px",
									}}
									variants={{
										bWAFpMR8m: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
										wh6wZzT4e: {
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											bWAFpMR8m: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "KAJVgh9jx",
																}}
																motionChild={true}
																nodeId={"oZTUMtXwZ"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"Contact Us"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
											wh6wZzT4e: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-g3gqkp"}
															data-styles-preset={"QbZRR8GOG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
															}}
														>
															<Link
																href={{
																	webPageId: "ObWQ0__Wh",
																}}
																motionChild={true}
																nodeId={"oZTUMtXwZ"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"QDDR7pqyK"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wxyf0f"}
																	data-styles-preset={"AV5lDhBeu"}
																>
																	{"Contact Us"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--framer-font-size": "14px",
												"--framer-line-height": "20px",
											}}
										>
											<motion.span
												style={{
													"--font-selector": "R0Y7RE0gU2Fucy1yZWd1bGFy",
													"--framer-font-family": '"DM Sans"',
													"--framer-font-size": "14px",
													"--framer-letter-spacing": "-0.01em",
													"--framer-text-color":
														"var(--extracted-1w3ko1f, rgba(20, 10, 62, 1))",
												}}
											>
												{"Contact Us"}
											</motion.span>
										</motion.p>
									</React.Fragment>
								</RichText>
								{isDisplayed4() && (
									<Link
										href={{
											webPageId: "ObWQ0__Wh",
										}}
										motionChild={true}
										nodeId={"H1Ow_DE4x"}
										scopeId={"QDDR7pqyK"}
									>
										<motion.a
											className={"framer-sbjxkb framer-16b58vx"}
											layoutDependency={layoutDependency}
											layoutId={"H1Ow_DE4x"}
										>
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "KAJVgh9jx",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															webPageId: "KAJVgh9jx",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks1) => (
													<ComponentViewportProvider
														height={44}
														{...addPropertyOverrides(
															{
																bWAFpMR8m: {
																	y:
																		(componentViewport?.y || 0) +
																		12 +
																		(((componentViewport?.height || 424) -
																			24 -
																			408) /
																			2 +
																			32 +
																			24) +
																		0 +
																		308 +
																		0,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-1q29oj8-container"}
															layoutDependency={layoutDependency}
															layoutId={"Id6qtNHov-container"}
															nodeId={"Id6qtNHov"}
															rendersWithMotion={true}
															scopeId={"QDDR7pqyK"}
														>
															{_jsx(stdin_default, {
																height: "100%",
																id: "Id6qtNHov",
																layoutId: "Id6qtNHov",
																rfFF_d5OS: "Get early access",
																RLoqfFjRC: resolvedLinks1[0],
																variant: matchVariant("e8dVm4yJw"),
																width: "100%",
																zjfJ_dvfV: false,
																...addPropertyOverrides(
																	{
																		bWAFpMR8m: {
																			RLoqfFjRC: resolvedLinks1[1],
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
										</motion.a>
									</Link>
								)}
							</motion.div>
						)}
					</motion.nav>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-OueQb.framer-16b58vx, .framer-OueQb .framer-16b58vx { display: block; }",
	".framer-OueQb.framer-9322as { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 16px 20px 16px 20px; position: relative; width: 1170px; }",
	".framer-OueQb .framer-22pcp { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-OueQb .framer-iiwkxi, .framer-OueQb .framer-sbjxkb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-OueQb .framer-l3x1g7 { cursor: pointer; flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-OueQb .framer-whm0ht, .framer-OueQb .framer-zgafj8 { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 4px; position: relative; width: min-content; }",
	".framer-OueQb .framer-1yygam7, .framer-OueQb .framer-f7gwlk { flex: none; height: 24px; position: relative; width: 24px; }",
	".framer-OueQb .framer-byswrc { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-OueQb .framer-1lc1t5b { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-OueQb .framer-1fvsp4b, .framer-OueQb .framer-65i2v0, .framer-OueQb .framer-affud3, .framer-OueQb .framer-frghuw, .framer-OueQb .framer-4v87py, .framer-OueQb .framer-frbvgx, .framer-OueQb .framer-1e14bh0, .framer-OueQb .framer-18n70lh, .framer-OueQb .framer-72auvo, .framer-OueQb .framer-9o6uvw, .framer-OueQb .framer-1leoh9, .framer-OueQb .framer-1iplzx9, .framer-OueQb .framer-y0hys9, .framer-OueQb .framer-fx8xlo { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-OueQb .framer-jevznv-container, .framer-OueQb .framer-1q29oj8-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-OueQb .framer-1t4hj1s { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-OueQb.framer-v-169ag3r.framer-9322as, .framer-OueQb.framer-v-k7rcim.framer-9322as { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 24px; padding: 12px 16px 12px 16px; width: 714px; }",
	".framer-OueQb.framer-v-169ag3r .framer-22pcp, .framer-OueQb.framer-v-k7rcim .framer-22pcp { flex: none; gap: 20px; justify-content: center; width: 100%; }",
	".framer-OueQb.framer-v-169ag3r .framer-iiwkxi, .framer-OueQb.framer-v-k7rcim .framer-iiwkxi { order: 0; }",
	".framer-OueQb.framer-v-169ag3r .framer-whm0ht { height: 36px; order: 3; width: 36px; }",
	".framer-OueQb.framer-v-169ag3r .framer-1yygam7, .framer-OueQb.framer-v-k7rcim .framer-f7gwlk { height: 20px; width: 20px; }",
	".framer-OueQb.framer-v-169ag3r .framer-byswrc { gap: 10px; order: 2; }",
	".framer-OueQb.framer-v-k7rcim .framer-zgafj8 { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 36px); order: 2; width: 36px; }",
	".framer-OueQb.framer-v-k7rcim .framer-byswrc, .framer-OueQb.framer-v-nqv0r .framer-iiwkxi { order: 1; }",
	".framer-OueQb.framer-v-k7rcim .framer-1t4hj1s, .framer-OueQb.framer-v-nqv0r .framer-1t4hj1s { align-content: flex-start; align-items: flex-start; }",
	".framer-OueQb.framer-v-vooqzl.framer-9322as, .framer-OueQb.framer-v-nqv0r.framer-9322as { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 24px; padding: 12px 16px 12px 16px; width: 350px; }",
	".framer-OueQb.framer-v-vooqzl .framer-22pcp, .framer-OueQb.framer-v-nqv0r .framer-22pcp { flex: none; width: 100%; }",
	".framer-OueQb.framer-v-vooqzl .framer-iiwkxi, .framer-OueQb.framer-v-nqv0r .framer-zgafj8 { order: 2; }",
	".framer-OueQb.framer-v-vooqzl .framer-whm0ht { order: 3; }",
	...css2,
	...css,
];
var FramerQDDR7pqyK = withCSS(Component, css3, "framer-OueQb");
var stdin_default2 = FramerQDDR7pqyK;
FramerQDDR7pqyK.displayName = "Nav";
FramerQDDR7pqyK.defaultProps = {
	height: 68,
	width: 1170,
};
addPropertyControls(FramerQDDR7pqyK, {
	variant: {
		options: ["emEdLZwHG", "NvFg_SNXZ", "wh6wZzT4e", "C2MKqmkz4", "bWAFpMR8m"],
		optionTitles: ["Desktop", "Tablet", "Tablet open", "Phone", "Phone open"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerQDDR7pqyK,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "DM Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "DM Sans",
					url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAopxhS2f3ZGMZpg.woff2",
					weight: "400",
				},
			],
		},
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerQDDR7pqyK.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:nav
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "C2MKqmkz4",
	md: "NvFg_SNXZ",
	xl: "emEdLZwHG",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var nav_default = ComponentWithRoot;
export { nav_default as default };
