// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 984c3bea485a0fa6 "Sassku - Creative SaaS and Startup Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: ' Desktop Team Card' | 'Tablet Team Card' | 'Phone Team Card' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * category?: string // Category
 * title?: string // Title
}} Props

 */
import { stdin_default } from "./chunks/chunk-XWPABNER.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-COXHTX6G.js";
import "./chunks/chunk-3UHWVJNE.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-PCEYUO2C.js";
import { className, css, fonts } from "./chunks/chunk-5CVYQU4P.js";
import { routes } from "./chunks/chunk-N7Y33TLT.js";

// virtual:team-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/76HV7OOL5Ytv1ZL4tNhM/6HLPPqnga7wFw3CDK0g1/wbPqAp3qo.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var SocialMediaFonts = getFonts(stdin_default);
var enabledGestures = {
	hCPEU5CgX: {
		hover: true,
	},
	jDoWqU0pf: {
		hover: true,
	},
	uVD4ltKK8: {
		hover: true,
	},
};
var cycleOrder = ["jDoWqU0pf", "hCPEU5CgX", "uVD4ltKK8"];
var serializationHash = "framer-CycqA";
var variantClassNames = {
	hCPEU5CgX: "framer-v-1n68ibf",
	jDoWqU0pf: "framer-v-1wbl8de",
	uVD4ltKK8: "framer-v-1i1rtu8",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	" Desktop Team Card": "jDoWqU0pf",
	"Phone Team Card": "uVD4ltKK8",
	"Tablet Team Card": "hCPEU5CgX",
};
var getProps = ({ category, height, id, image, title, width, ...props }) => {
	var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2, _ref3;
	return {
		...props,
		Aq39RuZby:
			(_ref = image !== null && image !== void 0 ? image : props.Aq39RuZby) !==
				null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/tjYol6zuwsHhJVXRpmmg9QBZ6YM.png?scale-down-to=512",
						srcSet:
							"https://framerusercontent.com/images/tjYol6zuwsHhJVXRpmmg9QBZ6YM.png?scale-down-to=1024 779w,https://framerusercontent.com/images/tjYol6zuwsHhJVXRpmmg9QBZ6YM.png 1096w",
					},
		DCsOibYIQ:
			(_ref1 = title !== null && title !== void 0 ? title : props.DCsOibYIQ) !==
				null && _ref1 !== void 0
				? _ref1
				: "Cody Fisher",
		variant:
			(_ref2 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref2 !== void 0
				? _ref2
				: "jDoWqU0pf",
		XRPGykFBe:
			(_ref3 =
				category !== null && category !== void 0
					? category
					: props.XRPGykFBe) !== null && _ref3 !== void 0
				? _ref3
				: "UI/UX Designer",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		Aq39RuZby,
		XRPGykFBe,
		DCsOibYIQ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureHandlers,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "jDoWqU0pf",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className2, className, className3];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1wbl8de",
							className4,
							classNames,
						)}
						data-framer-name={" Desktop Team Card"}
						layoutDependency={layoutDependency}
						layoutId={"jDoWqU0pf"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								"hCPEU5CgX-hover": {
									"data-framer-name": void 0,
								},
								"jDoWqU0pf-hover": {
									"data-framer-name": void 0,
								},
								"uVD4ltKK8-hover": {
									"data-framer-name": void 0,
								},
								hCPEU5CgX: {
									"data-framer-name": "Tablet Team Card",
								},
								uVD4ltKK8: {
									"data-framer-name": "Phone Team Card",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "stretch",
								sizes: `max(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"}, 1px)`,
								...toResponsiveImage(Aq39RuZby),
								...{
									positionX: "center",
									positionY: "center",
								},
							}}
							className={"framer-1j86i5o"}
							data-framer-name={"Image"}
							layoutDependency={layoutDependency}
							layoutId={"hrYsgx6zO"}
						/>
						<motion.div
							className={"framer-qn0xke"}
							data-framer-name={"Title Content Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"Lpo9JGZoF"}
							style={{
								background:
									'linear-gradient(180deg, rgba(20, 10, 61, 0) 0%, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)) /* {"name":"#140A3E"} */ 100%)',
							}}
						>
							<motion.div
								className={"framer-168wkir"}
								data-framer-name={"Content Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"MrTdoK6h5"}
								transformTemplate={transformTemplate1}
								{...addPropertyOverrides(
									{
										"uVD4ltKK8-hover": {
											transformTemplate: void 0,
										},
										uVD4ltKK8: {
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<motion.div
									className={"framer-19x7d7r"}
									data-framer-name={"Social Media"}
									layoutDependency={layoutDependency}
									layoutId={"tDy7mqAgc"}
									transformTemplate={transformTemplate1}
									{...addPropertyOverrides(
										{
											"hCPEU5CgX-hover": {
												transformTemplate: transformTemplate2,
											},
											"jDoWqU0pf-hover": {
												transformTemplate: transformTemplate2,
											},
											"uVD4ltKK8-hover": {
												transformTemplate: transformTemplate2,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<ComponentViewportProvider>
										<motion.div
											className={"framer-rsz5hs-container"}
											layoutDependency={layoutDependency}
											layoutId={"tcwQfg25c-container"}
										>
											{_jsx(stdin_default, {
												height: "100%",
												id: "tcwQfg25c",
												Js8mLgQ0i: "rgb(255, 255, 255)",
												L_62xNiYH: addImageAlt(
													{
														src: "https://framerusercontent.com/images/OaFIdx9NLCErcd5OeZu84PS0KqM.svg",
													},
													"",
												),
												layoutId: "tcwQfg25c",
												QXC_KWyEs: addImageAlt(
													{
														src: "https://framerusercontent.com/images/OaFIdx9NLCErcd5OeZu84PS0KqM.svg",
													},
													"",
												),
												uU2M21Aig: {
													borderColor:
														'var(--token-24c283da-fb76-4e7c-ad5e-249de576a67f, rgb(224, 225, 255)) /* {"name":"#E0E1FF"} */',
													borderStyle: "solid",
													borderWidth: 1,
												},
												variant: "Ned5NJR4g",
												width: "100%",
												Woto7Jn1Y:
													"https://www.framer.com/?via=anh72&gad_source=1&gclid=EAIaIQobChMIv_iJz7H4hgMVrRKDAx2HXQtoEAAYASAAEgLGNfD_BwE",
												xQEnTGEN_: "Facebook",
											})}
										</motion.div>
									</ComponentViewportProvider>
									<ComponentViewportProvider>
										<motion.div
											className={"framer-ysfbu1-container"}
											layoutDependency={layoutDependency}
											layoutId={"GdGorgicV-container"}
										>
											{_jsx(stdin_default, {
												height: "100%",
												id: "GdGorgicV",
												Js8mLgQ0i: "rgb(255, 255, 255)",
												L_62xNiYH: addImageAlt(
													{
														src: "https://framerusercontent.com/images/IoWBl0WSjDD9scrgnbJNZL1ySw.svg",
													},
													"",
												),
												layoutId: "GdGorgicV",
												QXC_KWyEs: addImageAlt(
													{
														src: "https://framerusercontent.com/images/IoWBl0WSjDD9scrgnbJNZL1ySw.svg",
													},
													"",
												),
												uU2M21Aig: {
													borderColor:
														'var(--token-24c283da-fb76-4e7c-ad5e-249de576a67f, rgb(224, 225, 255)) /* {"name":"#E0E1FF"} */',
													borderStyle: "solid",
													borderWidth: 1,
												},
												variant: "Ned5NJR4g",
												width: "100%",
												Woto7Jn1Y:
													"https://www.framer.com/?via=anh72&gad_source=1&gclid=EAIaIQobChMIv_iJz7H4hgMVrRKDAx2HXQtoEAAYASAAEgLGNfD_BwE",
												xQEnTGEN_: "Facebook",
											})}
										</motion.div>
									</ComponentViewportProvider>
									<ComponentViewportProvider>
										<motion.div
											className={"framer-qfjct5-container"}
											layoutDependency={layoutDependency}
											layoutId={"qMPUKe1Oc-container"}
										>
											{_jsx(stdin_default, {
												height: "100%",
												id: "qMPUKe1Oc",
												Js8mLgQ0i: "rgb(255, 255, 255)",
												L_62xNiYH: addImageAlt(
													{
														src: "https://framerusercontent.com/images/jUTm3JuFdbHJimj0Fov0hk3Pz4.svg",
													},
													"",
												),
												layoutId: "qMPUKe1Oc",
												QXC_KWyEs: addImageAlt(
													{
														src: "https://framerusercontent.com/images/jUTm3JuFdbHJimj0Fov0hk3Pz4.svg",
													},
													"",
												),
												uU2M21Aig: {
													borderColor:
														'var(--token-24c283da-fb76-4e7c-ad5e-249de576a67f, rgb(224, 225, 255)) /* {"name":"#E0E1FF"} */',
													borderStyle: "solid",
													borderWidth: 1,
												},
												variant: "Ned5NJR4g",
												width: "100%",
												Woto7Jn1Y:
													"https://www.framer.com/?via=anh72&gad_source=1&gclid=EAIaIQobChMIv_iJz7H4hgMVrRKDAx2HXQtoEAAYASAAEgLGNfD_BwE",
												xQEnTGEN_: "Facebook",
											})}
										</motion.div>
									</ComponentViewportProvider>
									<ComponentViewportProvider>
										<motion.div
											className={"framer-1f07cwi-container"}
											layoutDependency={layoutDependency}
											layoutId={"RYdUWAX_F-container"}
										>
											{_jsx(stdin_default, {
												height: "100%",
												id: "RYdUWAX_F",
												Js8mLgQ0i: "rgb(255, 255, 255)",
												L_62xNiYH: addImageAlt(
													{
														src: "https://framerusercontent.com/images/ioZHEnsbFZnpBRcBZqf1MbrV6Zo.svg",
													},
													"",
												),
												layoutId: "RYdUWAX_F",
												QXC_KWyEs: addImageAlt(
													{
														src: "https://framerusercontent.com/images/ioZHEnsbFZnpBRcBZqf1MbrV6Zo.svg",
													},
													"",
												),
												uU2M21Aig: {
													borderColor:
														'var(--token-24c283da-fb76-4e7c-ad5e-249de576a67f, rgb(224, 225, 255)) /* {"name":"#E0E1FF"} */',
													borderStyle: "solid",
													borderWidth: 1,
												},
												variant: "Ned5NJR4g",
												width: "100%",
												Woto7Jn1Y:
													"https://www.framer.com/?via=anh72&gad_source=1&gclid=EAIaIQobChMIv_iJz7H4hgMVrRKDAx2HXQtoEAAYASAAEgLGNfD_BwE",
												xQEnTGEN_: "Facebook",
											})}
										</motion.div>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-771pz0"}
									data-framer-name={"Name & Role"}
									layoutDependency={layoutDependency}
									layoutId={"v4hjpHpye"}
									transformTemplate={transformTemplate2}
									{...addPropertyOverrides(
										{
											"hCPEU5CgX-hover": {
												transformTemplate: void 0,
											},
											"jDoWqU0pf-hover": {
												transformTemplate: transformTemplate1,
											},
											"uVD4ltKK8-hover": {
												transformTemplate: transformTemplate1,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-m22f2p"}
										data-framer-name={"Subtitle"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"hn4aHlGXl"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-0637057f-bc88-4030-bf80-952e98872a3b, rgb(242, 246, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={XRPGykFBe}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-14owb4l"}
												data-styles-preset={"GB7NbXAgr"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-0637057f-bc88-4030-bf80-952e98872a3b, rgb(242, 246, 255)))",
												}}
											>
												{"UI/UX Designer"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-wfl0fa"}
										data-framer-name={"Title"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"YrD8Xr50z"}
										style={{
											"--extracted-1lwpl3i":
												"var(--token-c421066d-cdd9-4035-9b52-c69aa0d4f50c, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={DCsOibYIQ}
										variants={{
											uVD4ltKK8: {
												"--extracted-r6o4lv":
													"var(--token-c421066d-cdd9-4035-9b52-c69aa0d4f50c, rgb(255, 255, 255))",
											},
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												uVD4ltKK8: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-vv4slb"}
																data-styles-preset={"bbzL5FwFO"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-c421066d-cdd9-4035-9b52-c69aa0d4f50c, rgb(255, 255, 255)))",
																}}
															>
																{"Cody Fisher"}
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.h5
												className={"framer-styles-preset-1xzgfyq"}
												data-styles-preset={"dnf6oMP66"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1lwpl3i, var(--token-c421066d-cdd9-4035-9b52-c69aa0d4f50c, rgb(255, 255, 255)))",
												}}
											>
												{"Cody Fisher"}
											</motion.h5>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-CycqA.framer-1t1k78r, .framer-CycqA .framer-1t1k78r { display: block; }",
	".framer-CycqA.framer-1wbl8de { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 274px; }",
	".framer-CycqA .framer-1j86i5o { aspect-ratio: 0.7611111111111111 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 360px); position: relative; width: 1px; }",
	".framer-CycqA .framer-qn0xke { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; top: 0px; width: 100%; z-index: 1; }",
	".framer-CycqA .framer-168wkir { align-content: center; align-items: center; bottom: 20px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 50%; min-height: 54px; min-width: 234px; overflow: hidden; padding: 0px; position: absolute; width: min-content; }",
	".framer-CycqA .framer-19x7d7r { align-content: center; align-items: center; bottom: -25px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 0px; position: absolute; width: min-content; z-index: 1; }",
	".framer-CycqA .framer-rsz5hs-container, .framer-CycqA .framer-ysfbu1-container, .framer-CycqA .framer-qfjct5-container, .framer-CycqA .framer-1f07cwi-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-CycqA .framer-771pz0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: flex-start; left: 50%; overflow: visible; padding: 0px; position: absolute; top: 50%; width: 234px; z-index: 1; }",
	".framer-CycqA .framer-m22f2p, .framer-CycqA .framer-wfl0fa { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-CycqA.framer-1wbl8de, .framer-CycqA .framer-168wkir, .framer-CycqA .framer-19x7d7r, .framer-CycqA .framer-771pz0 { gap: 0px; } .framer-CycqA.framer-1wbl8de > *, .framer-CycqA .framer-168wkir > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-CycqA.framer-1wbl8de > :first-child, .framer-CycqA .framer-168wkir > :first-child, .framer-CycqA .framer-19x7d7r > :first-child { margin-left: 0px; } .framer-CycqA.framer-1wbl8de > :last-child, .framer-CycqA .framer-168wkir > :last-child, .framer-CycqA .framer-19x7d7r > :last-child { margin-right: 0px; } .framer-CycqA .framer-19x7d7r > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-CycqA .framer-771pz0 > * { margin: 0px; margin-bottom: calc(2px / 2); margin-top: calc(2px / 2); } .framer-CycqA .framer-771pz0 > :first-child { margin-top: 0px; } .framer-CycqA .framer-771pz0 > :last-child { margin-bottom: 0px; } }",
	".framer-CycqA.framer-v-1n68ibf.framer-1wbl8de { width: 230px; }",
	".framer-CycqA.framer-v-1n68ibf .framer-1j86i5o { aspect-ratio: 0.7876712328767124 / 1; height: var(--framer-aspect-ratio-supported, 292px); }",
	".framer-CycqA.framer-v-1n68ibf .framer-168wkir { min-width: 198px; }",
	".framer-CycqA.framer-v-1n68ibf .framer-771pz0 { width: 198px; }",
	".framer-CycqA.framer-v-1i1rtu8.framer-1wbl8de { width: 169px; }",
	".framer-CycqA.framer-v-1i1rtu8 .framer-1j86i5o { aspect-ratio: 0.7876712328767124 / 1; height: var(--framer-aspect-ratio-supported, 215px); }",
	".framer-CycqA.framer-v-1i1rtu8 .framer-168wkir { bottom: 16px; height: 46px; left: calc(50.29585798816571% - 145px / 2); min-height: unset; min-width: unset; width: 145px; }",
	".framer-CycqA.framer-v-1i1rtu8 .framer-19x7d7r { gap: 8px; }",
	".framer-CycqA.framer-v-1i1rtu8 .framer-771pz0 { top: 49%; width: 99%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-CycqA.framer-v-1i1rtu8 .framer-19x7d7r { gap: 0px; } .framer-CycqA.framer-v-1i1rtu8 .framer-19x7d7r > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-CycqA.framer-v-1i1rtu8 .framer-19x7d7r > :first-child { margin-left: 0px; } .framer-CycqA.framer-v-1i1rtu8 .framer-19x7d7r > :last-child { margin-right: 0px; } }",
	".framer-CycqA.framer-v-1wbl8de.hover .framer-19x7d7r, .framer-CycqA.framer-v-1n68ibf.hover .framer-19x7d7r { bottom: unset; top: 50%; }",
	".framer-CycqA.framer-v-1wbl8de.hover .framer-771pz0 { top: -48px; }",
	".framer-CycqA.framer-v-1n68ibf.hover .framer-771pz0 { left: unset; right: 0px; top: -55px; }",
	".framer-CycqA.framer-v-1i1rtu8.hover .framer-168wkir { min-height: unset; min-width: unset; }",
	".framer-CycqA.framer-v-1i1rtu8.hover .framer-19x7d7r { bottom: unset; left: 50%; top: 50%; }",
	".framer-CycqA.framer-v-1i1rtu8.hover .framer-771pz0 { left: 50%; top: -47px; }",
	...css2,
	...css,
	...css3,
];
var FramerwbPqAp3qo = withCSS(Component, css4, "framer-CycqA");
var stdin_default2 = FramerwbPqAp3qo;
FramerwbPqAp3qo.displayName = "Team Card";
FramerwbPqAp3qo.defaultProps = {
	height: 360,
	width: 274,
};
addPropertyControls(FramerwbPqAp3qo, {
	variant: {
		options: ["jDoWqU0pf", "hCPEU5CgX", "uVD4ltKK8"],
		optionTitles: [" Desktop Team Card", "Tablet Team Card", "Phone Team Card"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Aq39RuZby: {
		__defaultAssetReference:
			"data:framer/asset-reference,tjYol6zuwsHhJVXRpmmg9QBZ6YM.png?originalFilename=Image.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	XRPGykFBe: {
		defaultValue: "UI/UX Designer",
		displayTextArea: false,
		title: "Category",
		type: ControlType.String,
	},
	DCsOibYIQ: {
		defaultValue: "Cody Fisher",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerwbPqAp3qo,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...SocialMediaFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:team-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "hCPEU5CgX",
	xl: "jDoWqU0pf",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TeamCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var team_card_default = ComponentWithRoot;
export { team_card_default as default };
