// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 984c3bea485a0fa6 "Sassku - Creative SaaS and Startup Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' | 'SLIDESHOW' // Variant
 * text?: string // text
 * authorPhoto?: {src: string, srcSet?: string, alt?: string} // Author photo
 * authorName?: string // Author name
 * category?: string // Category
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-PCEYUO2C.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-SMK7VFXN.js";
import { className, css, fonts } from "./chunks/chunk-5CVYQU4P.js";
import { routes } from "./chunks/chunk-N7Y33TLT.js";

// virtual:testimonial-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ywXKv25fOqY7hj6mYk23/64uGg0s2PqNBOV95B922/TYbnHqXzN.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["RYbcA9L5s", "BhL8tckv9", "to2DOs9OZ", "IoYAvSHmB"];
var serializationHash = "framer-RGzpX";
var variantClassNames = {
	BhL8tckv9: "framer-v-1ygzo81",
	IoYAvSHmB: "framer-v-h22q4i",
	RYbcA9L5s: "framer-v-qb00fx",
	to2DOs9OZ: "framer-v-11l1doe",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "RYbcA9L5s",
	Phone: "to2DOs9OZ",
	SLIDESHOW: "IoYAvSHmB",
	Tablet: "BhL8tckv9",
};
var getProps = ({
	authorName,
	authorPhoto,
	category,
	height,
	id,
	text,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _ref3, _humanReadableVariantMap_props_variant, _ref4;
	return {
		...props,
		K4_BWCmLs:
			(_ref = text !== null && text !== void 0 ? text : props.K4_BWCmLs) !==
				null && _ref !== void 0
				? _ref
				: 'Incredible work! The team at Deflow transformed our outdated website into a sleek, modern masterpiece. Our site now  performs exceptionally well.  The team at Deflow transformed our outdated website into a sleek, modern masterpiece. Our site now  performs exceptionally well. website into a sleek, modern masterpiece. Highly recommend their services!"',
		kfCv3vezO:
			(_ref1 =
				category !== null && category !== void 0
					? category
					: props.kfCv3vezO) !== null && _ref1 !== void 0
				? _ref1
				: "Category",
		mUN0rNmUd:
			(_ref2 =
				authorName !== null && authorName !== void 0
					? authorName
					: props.mUN0rNmUd) !== null && _ref2 !== void 0
				? _ref2
				: "Author name",
		P0HWNnvTn:
			(_ref3 =
				authorPhoto !== null && authorPhoto !== void 0
					? authorPhoto
					: props.P0HWNnvTn) !== null && _ref3 !== void 0
				? _ref3
				: {
						src: "https://framerusercontent.com/images/mf19lKfm459fScuYgfrrG8Gqlo.svg",
					},
		variant:
			(_ref4 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref4 !== void 0
				? _ref4
				: "RYbcA9L5s",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		K4_BWCmLs,
		P0HWNnvTn,
		mUN0rNmUd,
		kfCv3vezO,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureHandlers,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "RYbcA9L5s",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className3, className, className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						aria-label={"Testimonial Card"}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-qb00fx",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"RYbcA9L5s"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor:
								"var(--token-c421066d-cdd9-4035-9b52-c69aa0d4f50c, rgb(255, 255, 255))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								BhL8tckv9: {
									"data-framer-name": "Tablet",
								},
								IoYAvSHmB: {
									"data-framer-name": "SLIDESHOW",
								},
								to2DOs9OZ: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<SVG
							className={"framer-se0ssq"}
							data-framer-name={"Icon"}
							fill={"rgba(0,0,0,1)"}
							intrinsicHeight={36}
							intrinsicWidth={36}
							layoutDependency={layoutDependency}
							layoutId={"ZPUy3tluy"}
							svg={
								'<svg width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g clip-path="url(#clip0_4651_250)">\n<path d="M28.125 22.5C26.5675 22.5 25.0449 22.0381 23.7499 21.1728C22.4549 20.3075 21.4455 19.0776 20.8495 17.6386C20.2534 16.1997 20.0975 14.6163 20.4013 13.0887C20.7052 11.5611 21.4552 10.1579 22.5565 9.05654C23.6579 7.9552 25.0611 7.20518 26.5887 6.90132C28.1163 6.59746 29.6997 6.75341 31.1386 7.34945C32.5776 7.94549 33.8075 8.95485 34.6728 10.2499C35.5381 11.5449 36 13.0675 36 14.625L36.036 15.75C36.036 17.8183 35.6286 19.8664 34.8371 21.7773C34.0456 23.6881 32.8855 25.4244 31.4229 26.8869C29.9604 28.3495 28.2241 29.5096 26.3133 30.3011C24.4024 31.0926 22.3543 31.5 20.286 31.5V27C21.764 27.004 23.2282 26.7149 24.5938 26.1495C25.9594 25.5841 27.1994 24.7536 28.242 23.706C28.6472 23.3015 29.0211 22.8668 29.3603 22.4055C28.9516 22.4697 28.5386 22.5021 28.125 22.5023V22.5ZM7.875 22.5C6.31748 22.5 4.79493 22.0381 3.49989 21.1728C2.20485 20.3075 1.19549 19.0776 0.599452 17.6386C0.00341217 16.1997 -0.152539 14.6163 0.151319 13.0887C0.455178 11.5611 1.2052 10.1579 2.30654 9.05654C3.40788 7.9552 4.81107 7.20518 6.33867 6.90132C7.86627 6.59746 9.44967 6.75341 10.8886 7.34945C12.3276 7.94549 13.5575 8.95485 14.4228 10.2499C15.2881 11.5449 15.75 13.0675 15.75 14.625L15.786 15.75C15.786 19.9272 14.1266 23.9332 11.1729 26.8869C8.21924 29.8406 4.21316 31.5 0.0360035 31.5V27C1.51402 27.004 2.97817 26.7149 4.34378 26.1495C5.70939 25.5841 6.94936 24.7536 7.992 23.706C8.39724 23.3015 8.77107 22.8668 9.11025 22.4055C8.70163 22.4697 8.28864 22.5021 7.875 22.5023V22.5Z" fill="#140A3E"/>\n</g>\n<defs>\n<clipPath id="clip0_4651_250">\n<rect width="36" height="36" fill="white"/>\n</clipPath>\n</defs>\n</svg>\n'
							}
							withExternalLayout={true}
						/>
						<motion.div
							className={"framer-190f0de"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"NWH7tQx3Q"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1pkuj8c"}
								data-framer-name={"Subtitle"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"fx5aS_wwU"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={K4_BWCmLs}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-g3gqkp"}
										data-styles-preset={"QbZRR8GOG"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)))",
										}}
									>
										{
											'Incredible work! The team at Deflow transformed our outdated website into a sleek, modern masterpiece. Our site now  performs exceptionally well.  The team at Deflow transformed our outdated website into a sleek, modern masterpiece. Our site now  performs exceptionally well. website into a sleek, modern masterpiece. Highly recommend their services!"'
										}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-7ibtx5"}
								data-framer-name={"User Info"}
								layoutDependency={layoutDependency}
								layoutId={"gtpPJyTMJ"}
							>
								<Image
									background={{
										alt: "",
										fit: "stretch",
										pixelHeight: 240,
										pixelWidth: 240,
										sizes: "60px",
										...toResponsiveImage(P0HWNnvTn),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-xfbctr"}
									data-framer-name={
										"young-woman-standing-with-her-arms-crossed"
									}
									layoutDependency={layoutDependency}
									layoutId={"JfZaBrYzg"}
									style={{
										borderBottomLeftRadius: 642,
										borderBottomRightRadius: 642,
										borderTopLeftRadius: 642,
										borderTopRightRadius: 642,
									}}
									{...addPropertyOverrides(
										{
											IoYAvSHmB: {
												background: {
													alt: "",
													fit: "stretch",
													pixelHeight: 240,
													pixelWidth: 240,
													sizes: "48px",
													...toResponsiveImage(P0HWNnvTn),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
											to2DOs9OZ: {
												background: {
													alt: "",
													fit: "stretch",
													pixelHeight: 240,
													pixelWidth: 240,
													sizes: "40px",
													...toResponsiveImage(P0HWNnvTn),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<motion.div
									className={"framer-1daxxpr"}
									data-framer-name={"User & Role"}
									layoutDependency={layoutDependency}
									layoutId={"sYnlpfBml"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1slaydx"}
										data-framer-name={"Rakib"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"BMc6RTEyb"}
										style={{
											"--extracted-1lwpl3i":
												"var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={mUN0rNmUd}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.h5
												className={"framer-styles-preset-1xzgfyq"}
												data-styles-preset={"dnf6oMP66"}
												style={{
													"--framer-text-color":
														"var(--extracted-1lwpl3i, var(--token-d1bdfefd-d741-45a8-a92b-5c125c1e0b5e, rgb(20, 10, 62)))",
												}}
											>
												{"Savannah Nguyen"}
											</motion.h5>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1i73wsn"}
										data-framer-name={"Lead at Design Kuthir"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"flp2jJ1Vi"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={kfCv3vezO}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												to2DOs9OZ: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-14owb4l"}
																data-styles-preset={"GB7NbXAgr"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
																}}
															>
																{"Category"}
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-g3gqkp"}
												data-styles-preset={"QbZRR8GOG"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-16ca65c9-955b-45e3-8564-516379125022, rgb(69, 76, 82)))",
												}}
											>
												{"Women's Bags"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-RGzpX.framer-1ls5wmz, .framer-RGzpX .framer-1ls5wmz { display: block; }",
	".framer-RGzpX.framer-qb00fx { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 40px; position: relative; width: 573px; }",
	".framer-RGzpX .framer-se0ssq { flex: none; height: 36px; position: relative; width: 36px; }",
	".framer-RGzpX .framer-190f0de { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-RGzpX .framer-1pkuj8c, .framer-RGzpX .framer-1slaydx { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-RGzpX .framer-7ibtx5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-RGzpX .framer-xfbctr { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 60px); position: relative; width: 60px; }",
	".framer-RGzpX .framer-1daxxpr { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-RGzpX .framer-1i73wsn { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-RGzpX.framer-qb00fx, .framer-RGzpX .framer-190f0de, .framer-RGzpX .framer-7ibtx5, .framer-RGzpX .framer-1daxxpr { gap: 0px; } .framer-RGzpX.framer-qb00fx > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-RGzpX.framer-qb00fx > :first-child, .framer-RGzpX .framer-190f0de > :first-child, .framer-RGzpX .framer-1daxxpr > :first-child { margin-top: 0px; } .framer-RGzpX.framer-qb00fx > :last-child, .framer-RGzpX .framer-190f0de > :last-child, .framer-RGzpX .framer-1daxxpr > :last-child { margin-bottom: 0px; } .framer-RGzpX .framer-190f0de > * { margin: 0px; margin-bottom: calc(20px / 2); margin-top: calc(20px / 2); } .framer-RGzpX .framer-7ibtx5 > * { margin: 0px; margin-left: calc(32px / 2); margin-right: calc(32px / 2); } .framer-RGzpX .framer-7ibtx5 > :first-child { margin-left: 0px; } .framer-RGzpX .framer-7ibtx5 > :last-child { margin-right: 0px; } .framer-RGzpX .framer-1daxxpr > * { margin: 0px; margin-bottom: calc(2px / 2); margin-top: calc(2px / 2); } }",
	".framer-RGzpX.framer-v-1ygzo81.framer-qb00fx { padding: 28px; width: 349px; }",
	".framer-RGzpX.framer-v-11l1doe.framer-qb00fx { gap: 16px; padding: 20px; width: 350px; }",
	".framer-RGzpX.framer-v-11l1doe .framer-se0ssq, .framer-RGzpX.framer-v-h22q4i .framer-se0ssq { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 24px); width: 24px; }",
	".framer-RGzpX.framer-v-11l1doe .framer-7ibtx5 { gap: 12px; }",
	".framer-RGzpX.framer-v-11l1doe .framer-xfbctr { height: var(--framer-aspect-ratio-supported, 40px); width: 40px; }",
	".framer-RGzpX.framer-v-11l1doe .framer-1daxxpr, .framer-RGzpX.framer-v-h22q4i .framer-1daxxpr { gap: 0px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-RGzpX.framer-v-11l1doe.framer-qb00fx, .framer-RGzpX.framer-v-11l1doe .framer-7ibtx5, .framer-RGzpX.framer-v-11l1doe .framer-1daxxpr { gap: 0px; } .framer-RGzpX.framer-v-11l1doe.framer-qb00fx > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-RGzpX.framer-v-11l1doe.framer-qb00fx > :first-child, .framer-RGzpX.framer-v-11l1doe .framer-1daxxpr > :first-child { margin-top: 0px; } .framer-RGzpX.framer-v-11l1doe.framer-qb00fx > :last-child, .framer-RGzpX.framer-v-11l1doe .framer-1daxxpr > :last-child { margin-bottom: 0px; } .framer-RGzpX.framer-v-11l1doe .framer-7ibtx5 > * { margin: 0px; margin-left: calc(12px / 2); margin-right: calc(12px / 2); } .framer-RGzpX.framer-v-11l1doe .framer-7ibtx5 > :first-child { margin-left: 0px; } .framer-RGzpX.framer-v-11l1doe .framer-7ibtx5 > :last-child { margin-right: 0px; } .framer-RGzpX.framer-v-11l1doe .framer-1daxxpr > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } }",
	".framer-RGzpX.framer-v-h22q4i.framer-qb00fx { gap: 20px; padding: 32px 28px 32px 28px; width: 462px; }",
	".framer-RGzpX.framer-v-h22q4i .framer-190f0de { gap: 24px; }",
	".framer-RGzpX.framer-v-h22q4i .framer-7ibtx5 { gap: 16px; }",
	".framer-RGzpX.framer-v-h22q4i .framer-xfbctr { height: var(--framer-aspect-ratio-supported, 48px); width: 48px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-RGzpX.framer-v-h22q4i.framer-qb00fx, .framer-RGzpX.framer-v-h22q4i .framer-190f0de, .framer-RGzpX.framer-v-h22q4i .framer-7ibtx5, .framer-RGzpX.framer-v-h22q4i .framer-1daxxpr { gap: 0px; } .framer-RGzpX.framer-v-h22q4i.framer-qb00fx > * { margin: 0px; margin-bottom: calc(20px / 2); margin-top: calc(20px / 2); } .framer-RGzpX.framer-v-h22q4i.framer-qb00fx > :first-child, .framer-RGzpX.framer-v-h22q4i .framer-190f0de > :first-child, .framer-RGzpX.framer-v-h22q4i .framer-1daxxpr > :first-child { margin-top: 0px; } .framer-RGzpX.framer-v-h22q4i.framer-qb00fx > :last-child, .framer-RGzpX.framer-v-h22q4i .framer-190f0de > :last-child, .framer-RGzpX.framer-v-h22q4i .framer-1daxxpr > :last-child { margin-bottom: 0px; } .framer-RGzpX.framer-v-h22q4i .framer-190f0de > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-RGzpX.framer-v-h22q4i .framer-7ibtx5 > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-RGzpX.framer-v-h22q4i .framer-7ibtx5 > :first-child { margin-left: 0px; } .framer-RGzpX.framer-v-h22q4i .framer-7ibtx5 > :last-child { margin-right: 0px; } .framer-RGzpX.framer-v-h22q4i .framer-1daxxpr > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } }",
	...css3,
	...css,
	...css2,
];
var FramerTYbnHqXzN = withCSS(Component, css4, "framer-RGzpX");
var stdin_default = FramerTYbnHqXzN;
FramerTYbnHqXzN.displayName = "Testimonial Card";
FramerTYbnHqXzN.defaultProps = {
	height: 320,
	width: 573,
};
addPropertyControls(FramerTYbnHqXzN, {
	variant: {
		options: ["RYbcA9L5s", "BhL8tckv9", "to2DOs9OZ", "IoYAvSHmB"],
		optionTitles: ["Desktop", "Tablet", "Phone", "SLIDESHOW"],
		title: "Variant",
		type: ControlType.Enum,
	},
	K4_BWCmLs: {
		defaultValue:
			'Incredible work! The team at Deflow transformed our outdated website into a sleek, modern masterpiece. Our site now  performs exceptionally well.  The team at Deflow transformed our outdated website into a sleek, modern masterpiece. Our site now  performs exceptionally well. website into a sleek, modern masterpiece. Highly recommend their services!"',
		title: "text",
		type: ControlType.String,
	},
	P0HWNnvTn: {
		__defaultAssetReference:
			"data:framer/asset-reference,mf19lKfm459fScuYgfrrG8Gqlo.svg?originalFilename=young-woman-standing-with-her-arms-crosseda.svg&preferredSize=auto",
		title: "Author photo",
		type: ControlType.ResponsiveImage,
	},
	mUN0rNmUd: {
		defaultValue: "Author name",
		title: "Author name",
		type: ControlType.String,
	},
	kfCv3vezO: {
		defaultValue: "Category",
		title: "Category",
		type: ControlType.String,
	},
});
addFonts(
	FramerTYbnHqXzN,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:testimonial-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "BhL8tckv9",
	xl: "RYbcA9L5s",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TestimonialCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"984c3bea485a0fa69afc0c4e9df674606559dc1aa30c4eb2640e8d08de7360b2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var testimonial_card_default = ComponentWithRoot;
export { testimonial_card_default as default };
